
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-02-19T17:00:48+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf0ce43e8f9e7c57e173631d2526c873186324e9",
 "version": "4.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
