
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-05T13:07:42+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a6f6086469adf7b6b0028a2fd6ec3316d954b5b9",
 "version": "1.0.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
