import os,sys,typer
current_file_path=os.path.abspath(__file__)
parent_directory=os.path.dirname(current_file_path)
sys.path.insert(0,parent_directory)
app=typer.Typer()
@app.command()
def sparta_963d30da2e(port=None,background=True):spartaqube_cli.list()
@app.command()
def sparta_d421041608():spartaqube_cli.list()
@app.command()
def sparta_56c0339a25():spartaqube_cli.sparta_56c0339a25()
@app.command()
def sparta_2d8e5a368c():print('Hello world!')
if __name__=='__main__':app()