# Generated by Django 5.1.4 on 2024-12-29 20:24

import crimsonslate_portfolio.validators
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimsonslate_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='source',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='', validators=[crimsonslate_portfolio.validators.validate_media_file_extension]),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumb',
            field=models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='thumbnail'),
        ),
        migrations.CreateModel(
            name='MediaSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='source/')),
                ('media', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crimsonslate_portfolio.media', validators=[crimsonslate_portfolio.validators.validate_media_file_extension])),
            ],
        ),
    ]
