from .misc import weighted_error_mean_and_std, rolling_mean
from .plot_utilities import boldify_legend_text, get_regression_line_soft_range_of_interest_intersections
from .math_utilities import nearest_ceiling_idx, nearest_idx