
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-04T10:20:58-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "619a878d2ad3c12258dccc2a3be75e92ad2b1622",
 "version": "2025.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
