# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.vetric_marketplace_search_response_data_marketplace_search_feed_units_edges_inner_node_photo_default_image import VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage

class TestVetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage(unittest.TestCase):
    """VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage:
        """Test VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage`
        """
        model = VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage()
        if include_optional:
            return VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage(
                height = 56,
                width = 56,
                uri = ''
            )
        else:
            return VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage(
        )
        """

    def testVetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage(self):
        """Test VetricMarketplaceSearchResponseDataMarketplaceSearchFeedUnitsEdgesInnerNodePhotoDefaultImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
