# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.redemption_summary import RedemptionSummary

class TestRedemptionSummary(unittest.TestCase):
    """RedemptionSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RedemptionSummary:
        """Test RedemptionSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RedemptionSummary`
        """
        model = RedemptionSummary()
        if include_optional:
            return RedemptionSummary(
                receiver_total = '',
                value = '',
                fee = ''
            )
        else:
            return RedemptionSummary(
        )
        """

    def testRedemptionSummary(self):
        """Test RedemptionSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
