# coding: utf-8

"""
    Skyfire API

    The Skyfire API is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.open_router_create_chat_completion_request import OpenRouterCreateChatCompletionRequest

class TestOpenRouterCreateChatCompletionRequest(unittest.TestCase):
    """OpenRouterCreateChatCompletionRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenRouterCreateChatCompletionRequest:
        """Test OpenRouterCreateChatCompletionRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenRouterCreateChatCompletionRequest`
        """
        model = OpenRouterCreateChatCompletionRequest()
        if include_optional:
            return OpenRouterCreateChatCompletionRequest(
                messages = [
                    skyfire_sdk.models.chat_completion_request_message.ChatCompletionRequestMessage(
                        role = 'user', 
                        content = 'Hello, how are you?', 
                        name = '', )
                    ],
                model = 'anthropic/claude-3.5-sonnet',
                frequency_penalty = -2,
                logit_bias = {
                    'key' : 56
                    },
                logprobs = True,
                top_logprobs = 0,
                max_tokens = 56,
                n = 1,
                presence_penalty = -2,
                response_format = skyfire_sdk.models.create_chat_completion_request_response_format.CreateChatCompletionRequest_response_format(
                    type = 'text', ),
                seed = -9223372036854776000,
                service_tier = '',
                stop = None,
                stream = True,
                stream_options = skyfire_sdk.models.chat_completion_stream_options.ChatCompletionStreamOptions(
                    include_usage = True, ),
                temperature = 1,
                top_p = 1,
                tools = [
                    skyfire_sdk.models.chat_completion_tool.ChatCompletionTool(
                        type = '', 
                        function = skyfire_sdk.models.function_object.FunctionObject(
                            description = '', 
                            name = '', 
                            parameters = { }, ), )
                    ],
                tool_choice = None,
                transforms = [
                    ''
                    ],
                models = [
                    ''
                    ],
                route = '',
                parallel_tool_calls = True,
                user = 'user-1234',
                function_call = None,
                functions = None
            )
        else:
            return OpenRouterCreateChatCompletionRequest(
                messages = [
                    skyfire_sdk.models.chat_completion_request_message.ChatCompletionRequestMessage(
                        role = 'user', 
                        content = 'Hello, how are you?', 
                        name = '', )
                    ],
                model = 'anthropic/claude-3.5-sonnet',
        )
        """

    def testOpenRouterCreateChatCompletionRequest(self):
        """Test OpenRouterCreateChatCompletionRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
