# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.api.open_router_api import OpenRouterApi


class TestOpenRouterApi(unittest.TestCase):
    """OpenRouterApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OpenRouterApi()

    def tearDown(self) -> None:
        pass

    def test_create_open_router_chat_completion(self) -> None:
        """Test case for create_open_router_chat_completion

        Creates a model response for the given chat conversation.
        """
        pass


if __name__ == '__main__':
    unittest.main()
