# coding: utf-8

"""
    Skyfire API

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.net_nut_response import NetNutResponse

class TestNetNutResponse(unittest.TestCase):
    """NetNutResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NetNutResponse:
        """Test NetNutResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NetNutResponse`
        """
        model = NetNutResponse()
        if include_optional:
            return NetNutResponse(
                success = True,
                message = ''
            )
        else:
            return NetNutResponse(
                success = True,
                message = '',
        )
        """

    def testNetNutResponse(self):
        """Test NetNutResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
