# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.api.organization_api import OrganizationApi


class TestOrganizationApi(unittest.TestCase):
    """OrganizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization(self) -> None:
        """Test case for create_organization

        Create Organization
        """
        pass

    def test_create_organization_user(self) -> None:
        """Test case for create_organization_user

        Create User
        """
        pass

    def test_create_primary_eth_wallet(self) -> None:
        """Test case for create_primary_eth_wallet

        Create Wallet
        """
        pass

    def test_delete_organization(self) -> None:
        """Test case for delete_organization

        Delete Organization By ID
        """
        pass

    def test_delete_organization_by_name(self) -> None:
        """Test case for delete_organization_by_name

        Delete Organization By Name
        """
        pass

    def test_delete_wallet_endpoint(self) -> None:
        """Test case for delete_wallet_endpoint

        Delete Wallet
        """
        pass

    def test_enterprise_admin_create_bridge_virtual_account(self) -> None:
        """Test case for enterprise_admin_create_bridge_virtual_account

        Create ACH Account
        """
        pass

    def test_enterprise_admin_deactivate_bridge_virtual_account(self) -> None:
        """Test case for enterprise_admin_deactivate_bridge_virtual_account

        Deactivate ACH Account
        """
        pass

    def test_enterprise_admin_reactivate_bridge_virtual_account(self) -> None:
        """Test case for enterprise_admin_reactivate_bridge_virtual_account

        Reactivate ACH Account
        """
        pass

    def test_enterprise_delete_api_key_for_user(self) -> None:
        """Test case for enterprise_delete_api_key_for_user

        Delete API Key
        """
        pass

    def test_enterprise_generate_api_key_for_user(self) -> None:
        """Test case for enterprise_generate_api_key_for_user

        Create API Key
        """
        pass

    def test_enterprise_get_api_key_for_user(self) -> None:
        """Test case for enterprise_get_api_key_for_user

        Get All API Keys
        """
        pass

    def test_get_organization_user(self) -> None:
        """Test case for get_organization_user

        Get User
        """
        pass

    def test_get_organization_users(self) -> None:
        """Test case for get_organization_users

        Get Organization By ID
        """
        pass

    def test_get_organization_users_by_id(self) -> None:
        """Test case for get_organization_users_by_id

        Get Users by Org ID
        """
        pass

    def test_get_organization_users_by_name(self) -> None:
        """Test case for get_organization_users_by_name

        Get Users by Org Name
        """
        pass

    def test_get_organizations(self) -> None:
        """Test case for get_organizations

        Get Organizations
        """
        pass

    def test_switch_default_by_wallet_id_endpoint(self) -> None:
        """Test case for switch_default_by_wallet_id_endpoint

        Switch Default Wallet
        """
        pass

    def test_validate_group_payment(self) -> None:
        """Test case for validate_group_payment

        Validate Payment
        """
        pass


if __name__ == '__main__':
    unittest.main()
