# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.vetric_instagram_location_map_response_pins_inner_page_info import VetricInstagramLocationMapResponsePinsInnerPageInfo

class TestVetricInstagramLocationMapResponsePinsInnerPageInfo(unittest.TestCase):
    """VetricInstagramLocationMapResponsePinsInnerPageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VetricInstagramLocationMapResponsePinsInnerPageInfo:
        """Test VetricInstagramLocationMapResponsePinsInnerPageInfo
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VetricInstagramLocationMapResponsePinsInnerPageInfo`
        """
        model = VetricInstagramLocationMapResponsePinsInnerPageInfo()
        if include_optional:
            return VetricInstagramLocationMapResponsePinsInnerPageInfo(
                location_id = '',
                facebook_places_id = '',
                name = '',
                phone = '',
                website = '',
                category = '',
                price_range = 56,
                hours = skyfire_sdk.models.vetric_instagram_location_map_response_pins_inner_page_info_hours.VetricInstagramLocationMapResponse_pins_inner_page_info_hours(
                    status = '', 
                    current_status = '', 
                    hours_today = '', 
                    schedule = [
                        skyfire_sdk.models.vetric_instagram_location_map_response_pins_inner_page_info_hours_schedule_inner.VetricInstagramLocationMapResponse_pins_inner_page_info_hours_schedule_inner(
                            day_of_week = '', 
                            hours = [
                                ''
                                ], )
                        ], 
                    is_open = True, ),
                location_address = '',
                location_city = '',
                location_zip = '',
                num_guides = 56,
                has_menu = True,
                page_effect_info = skyfire_sdk.models.vetric_instagram_location_map_response_pins_inner_page_info_page_effect_info.VetricInstagramLocationMapResponse_pins_inner_page_info_page_effect_info(
                    num_effects = 56, 
                    thumbnail_url = '', )
            )
        else:
            return VetricInstagramLocationMapResponsePinsInnerPageInfo(
        )
        """

    def testVetricInstagramLocationMapResponsePinsInnerPageInfo(self):
        """Test VetricInstagramLocationMapResponsePinsInnerPageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
