# coding: utf-8

"""
    Skyfire API

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.custody_provider import CustodyProvider

class TestCustodyProvider(unittest.TestCase):
    """CustodyProvider unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCustodyProvider(self):
        """Test CustodyProvider"""
        # inst = CustodyProvider()

if __name__ == '__main__':
    unittest.main()
