# coding: utf-8

"""
    Skyfire API

    The Skyfire API is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.reloadly_gift_card_response_product_brand import ReloadlyGiftCardResponseProductBrand

class TestReloadlyGiftCardResponseProductBrand(unittest.TestCase):
    """ReloadlyGiftCardResponseProductBrand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReloadlyGiftCardResponseProductBrand:
        """Test ReloadlyGiftCardResponseProductBrand
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReloadlyGiftCardResponseProductBrand`
        """
        model = ReloadlyGiftCardResponseProductBrand()
        if include_optional:
            return ReloadlyGiftCardResponseProductBrand(
                brand_name = '',
                brand_id = 1.337
            )
        else:
            return ReloadlyGiftCardResponseProductBrand(
                brand_name = '',
                brand_id = 1.337,
        )
        """

    def testReloadlyGiftCardResponseProductBrand(self):
        """Test ReloadlyGiftCardResponseProductBrand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
