# coding: utf-8

"""
    Skyfire API

    The Skyfire API is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.api.toolkit_api import ToolkitApi


class TestToolkitApi(unittest.TestCase):
    """ToolkitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ToolkitApi()

    def tearDown(self) -> None:
        pass

    def test_send_email(self) -> None:
        """Test case for send_email

        """
        pass


if __name__ == '__main__':
    unittest.main()
