# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.organization_response import OrganizationResponse

class TestOrganizationResponse(unittest.TestCase):
    """OrganizationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrganizationResponse:
        """Test OrganizationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrganizationResponse`
        """
        model = OrganizationResponse()
        if include_optional:
            return OrganizationResponse(
                organization = skyfire_sdk.models.organization.Organization(
                    id = '', 
                    name = '', 
                    admin_user_id = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    #wallets = [
                        skyfire_sdk.models.wallet.Wallet(
                            id = '', 
                            user_id = '', 
                            organization_id = '', 
                            wallet_name = '', 
                            is_default = True, 
                            is_smart = True, 
                            custody_provider = 'SKYFIRE_EVERVAULT', 
                            wallet_type = 'Sender', 
                            network = 'polygon_testnet', 
                            wallet_address = '', 
                            bridge_virtual_account = skyfire_sdk.models.bridge_virtual_account.BridgeVirtualAccount(
                                id = '', 
                                status = 'activated', 
                                customer_id = '', 
                                source_deposit_instructions = skyfire_sdk.models.bridge_source_deposit_address.BridgeSourceDepositAddress(
                                    currency = '', 
                                    bank_beneficiary_name = '', 
                                    bank_name = '', 
                                    bank_address = '', 
                                    bank_routing_number = '', 
                                    bank_account_number = '', 
                                    payment_rails = [
                                        ''
                                        ], ), 
                                destination = skyfire_sdk.models.bridge_destination.BridgeDestination(
                                    currency = 'usd', 
                                    payment_rail = 'usdc', 
                                    address = '0xC', ), ), 
                            bridge_virtual_account_id = '', 
                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            #skyfire_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                                id = '', 
                                username = '', 
                                email = '', 
                                is_admin = True, 
                                is_enterprise_admin = True, 
                                is_active = True, 
                                is_onboarded = True, 
                                user_type = 'Sender', 
                                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                attributes = null, 
                                parent_user_id = '', 
                                stytch_user_id = '', 
                                stripe_customer_id = '', 
                                rules = [
                                    skyfire_sdk.models.user_rule.UserRule(
                                        id = '', 
                                        type = 'DURATION', 
                                        frequency = 'DAILY', 
                                        target_wallet_address = '', 
                                        amount = '', )
                                    ], 
                                #parent_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                                    id = '', 
                                    username = '', 
                                    email = '', 
                                    is_admin = True, 
                                    is_enterprise_admin = True, 
                                    is_active = True, 
                                    is_onboarded = True, 
                                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    attributes = null, 
                                    parent_user_id = '', 
                                    stytch_user_id = '', 
                                    stripe_customer_id = '', 
                                    #user_organizations = [
                                        skyfire_sdk.models.user_organization.UserOrganization(
                                            id = 1.337, 
                                            user_id = '', 
                                            organization_id = '', 
                                            attributes = null, 
                                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                        ], 
                                    #default_wallet = skyfire_sdk.models.wallet.Wallet(
                                        id = '', 
                                        user_id = '', 
                                        organization_id = '', 
                                        wallet_name = '', 
                                        is_default = True, 
                                        is_smart = True, 
                                        custody_provider = 'SKYFIRE_EVERVAULT', 
                                        wallet_type = 'Sender', 
                                        network = 'polygon_testnet', 
                                        wallet_address = '', 
                                        bridge_virtual_account_id = '', 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        #organization = skyfire_sdk.models.organization.Organization(
                                            id = '', 
                                            name = '', 
                                            admin_user_id = '', 
                                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), ), 
                                    #organization_wallets = [
                                        
                                        ], 
                                    #created_organizations = [
                                        
                                        ], ), 
                                #user_organizations = [
                                    skyfire_sdk.models.user_organization.UserOrganization(
                                        id = 1.337, 
                                        user_id = '', 
                                        organization_id = '', 
                                        attributes = null, 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], 
                                #default_wallet = , 
                                #organization_wallets = [
                                    
                                    ], 
                                #created_organizations = [
                                    
                                    ], ), 
                            #organization = , )
                        ], 
                    #user_organizations = , ),
                wallets = [
                    skyfire_sdk.models.wallet.Wallet(
                        id = '', 
                        user_id = '', 
                        organization_id = '', 
                        wallet_name = '', 
                        is_default = True, 
                        is_smart = True, 
                        custody_provider = 'SKYFIRE_EVERVAULT', 
                        wallet_type = 'Sender', 
                        network = 'polygon_testnet', 
                        wallet_address = '', 
                        bridge_virtual_account = skyfire_sdk.models.bridge_virtual_account.BridgeVirtualAccount(
                            id = '', 
                            status = 'activated', 
                            customer_id = '', 
                            source_deposit_instructions = skyfire_sdk.models.bridge_source_deposit_address.BridgeSourceDepositAddress(
                                currency = '', 
                                bank_beneficiary_name = '', 
                                bank_name = '', 
                                bank_address = '', 
                                bank_routing_number = '', 
                                bank_account_number = '', 
                                payment_rails = [
                                    ''
                                    ], ), 
                            destination = skyfire_sdk.models.bridge_destination.BridgeDestination(
                                currency = 'usd', 
                                payment_rail = 'usdc', 
                                address = '0xC', ), ), 
                        bridge_virtual_account_id = '', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        #skyfire_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                            id = '', 
                            username = '', 
                            email = '', 
                            is_admin = True, 
                            is_enterprise_admin = True, 
                            is_active = True, 
                            is_onboarded = True, 
                            user_type = 'Sender', 
                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            attributes = null, 
                            parent_user_id = '', 
                            stytch_user_id = '', 
                            stripe_customer_id = '', 
                            rules = [
                                skyfire_sdk.models.user_rule.UserRule(
                                    id = '', 
                                    type = 'DURATION', 
                                    frequency = 'DAILY', 
                                    target_wallet_address = '', 
                                    amount = '', )
                                ], 
                            #parent_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                                id = '', 
                                username = '', 
                                email = '', 
                                is_admin = True, 
                                is_enterprise_admin = True, 
                                is_active = True, 
                                is_onboarded = True, 
                                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                attributes = null, 
                                parent_user_id = '', 
                                stytch_user_id = '', 
                                stripe_customer_id = '', 
                                #user_organizations = [
                                    skyfire_sdk.models.user_organization.UserOrganization(
                                        id = 1.337, 
                                        user_id = '', 
                                        organization_id = '', 
                                        attributes = null, 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], 
                                #wallets = [
                                    skyfire_sdk.models.wallet.Wallet(
                                        id = '', 
                                        user_id = '', 
                                        organization_id = '', 
                                        wallet_name = '', 
                                        is_default = True, 
                                        is_smart = True, 
                                        custody_provider = 'SKYFIRE_EVERVAULT', 
                                        wallet_type = 'Sender', 
                                        network = 'polygon_testnet', 
                                        wallet_address = '', 
                                        bridge_virtual_account_id = '', 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        #organization = skyfire_sdk.models.organization.Organization(
                                            id = '', 
                                            name = '', 
                                            admin_user_id = '', 
                                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                                    ], 
                                #default_wallet = , 
                                #organization_wallets = [
                                    
                                    ], 
                                #created_organizations = [
                                    skyfire_sdk.models.organization.Organization(
                                        id = '', 
                                        name = '', 
                                        admin_user_id = '', 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], ), 
                            #user_organizations = [
                                skyfire_sdk.models.user_organization.UserOrganization(
                                    id = 1.337, 
                                    user_id = '', 
                                    organization_id = '', 
                                    attributes = null, 
                                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            #wallets = [
                                
                                ], 
                            #default_wallet = , 
                            #organization_wallets = [
                                
                                ], 
                            #created_organizations = [
                                
                                ], ), 
                        #organization = , )
                    ]
            )
        else:
            return OrganizationResponse(
                organization = skyfire_sdk.models.organization.Organization(
                    id = '', 
                    name = '', 
                    admin_user_id = '', 
                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    #wallets = [
                        skyfire_sdk.models.wallet.Wallet(
                            id = '', 
                            user_id = '', 
                            organization_id = '', 
                            wallet_name = '', 
                            is_default = True, 
                            is_smart = True, 
                            custody_provider = 'SKYFIRE_EVERVAULT', 
                            wallet_type = 'Sender', 
                            network = 'polygon_testnet', 
                            wallet_address = '', 
                            bridge_virtual_account = skyfire_sdk.models.bridge_virtual_account.BridgeVirtualAccount(
                                id = '', 
                                status = 'activated', 
                                customer_id = '', 
                                source_deposit_instructions = skyfire_sdk.models.bridge_source_deposit_address.BridgeSourceDepositAddress(
                                    currency = '', 
                                    bank_beneficiary_name = '', 
                                    bank_name = '', 
                                    bank_address = '', 
                                    bank_routing_number = '', 
                                    bank_account_number = '', 
                                    payment_rails = [
                                        ''
                                        ], ), 
                                destination = skyfire_sdk.models.bridge_destination.BridgeDestination(
                                    currency = 'usd', 
                                    payment_rail = 'usdc', 
                                    address = '0xC', ), ), 
                            bridge_virtual_account_id = '', 
                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            #skyfire_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                                id = '', 
                                username = '', 
                                email = '', 
                                is_admin = True, 
                                is_enterprise_admin = True, 
                                is_active = True, 
                                is_onboarded = True, 
                                user_type = 'Sender', 
                                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                attributes = null, 
                                parent_user_id = '', 
                                stytch_user_id = '', 
                                stripe_customer_id = '', 
                                rules = [
                                    skyfire_sdk.models.user_rule.UserRule(
                                        id = '', 
                                        type = 'DURATION', 
                                        frequency = 'DAILY', 
                                        target_wallet_address = '', 
                                        amount = '', )
                                    ], 
                                #parent_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                                    id = '', 
                                    username = '', 
                                    email = '', 
                                    is_admin = True, 
                                    is_enterprise_admin = True, 
                                    is_active = True, 
                                    is_onboarded = True, 
                                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    attributes = null, 
                                    parent_user_id = '', 
                                    stytch_user_id = '', 
                                    stripe_customer_id = '', 
                                    #user_organizations = [
                                        skyfire_sdk.models.user_organization.UserOrganization(
                                            id = 1.337, 
                                            user_id = '', 
                                            organization_id = '', 
                                            attributes = null, 
                                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                        ], 
                                    #default_wallet = skyfire_sdk.models.wallet.Wallet(
                                        id = '', 
                                        user_id = '', 
                                        organization_id = '', 
                                        wallet_name = '', 
                                        is_default = True, 
                                        is_smart = True, 
                                        custody_provider = 'SKYFIRE_EVERVAULT', 
                                        wallet_type = 'Sender', 
                                        network = 'polygon_testnet', 
                                        wallet_address = '', 
                                        bridge_virtual_account_id = '', 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        #organization = skyfire_sdk.models.organization.Organization(
                                            id = '', 
                                            name = '', 
                                            admin_user_id = '', 
                                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), ), 
                                    #organization_wallets = [
                                        
                                        ], 
                                    #created_organizations = [
                                        
                                        ], ), 
                                #user_organizations = [
                                    skyfire_sdk.models.user_organization.UserOrganization(
                                        id = 1.337, 
                                        user_id = '', 
                                        organization_id = '', 
                                        attributes = null, 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], 
                                #default_wallet = , 
                                #organization_wallets = [
                                    
                                    ], 
                                #created_organizations = [
                                    
                                    ], ), 
                            #organization = , )
                        ], 
                    #user_organizations = , ),
                wallets = [
                    skyfire_sdk.models.wallet.Wallet(
                        id = '', 
                        user_id = '', 
                        organization_id = '', 
                        wallet_name = '', 
                        is_default = True, 
                        is_smart = True, 
                        custody_provider = 'SKYFIRE_EVERVAULT', 
                        wallet_type = 'Sender', 
                        network = 'polygon_testnet', 
                        wallet_address = '', 
                        bridge_virtual_account = skyfire_sdk.models.bridge_virtual_account.BridgeVirtualAccount(
                            id = '', 
                            status = 'activated', 
                            customer_id = '', 
                            source_deposit_instructions = skyfire_sdk.models.bridge_source_deposit_address.BridgeSourceDepositAddress(
                                currency = '', 
                                bank_beneficiary_name = '', 
                                bank_name = '', 
                                bank_address = '', 
                                bank_routing_number = '', 
                                bank_account_number = '', 
                                payment_rails = [
                                    ''
                                    ], ), 
                            destination = skyfire_sdk.models.bridge_destination.BridgeDestination(
                                currency = 'usd', 
                                payment_rail = 'usdc', 
                                address = '0xC', ), ), 
                        bridge_virtual_account_id = '', 
                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        #skyfire_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                            id = '', 
                            username = '', 
                            email = '', 
                            is_admin = True, 
                            is_enterprise_admin = True, 
                            is_active = True, 
                            is_onboarded = True, 
                            user_type = 'Sender', 
                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            attributes = null, 
                            parent_user_id = '', 
                            stytch_user_id = '', 
                            stripe_customer_id = '', 
                            rules = [
                                skyfire_sdk.models.user_rule.UserRule(
                                    id = '', 
                                    type = 'DURATION', 
                                    frequency = 'DAILY', 
                                    target_wallet_address = '', 
                                    amount = '', )
                                ], 
                            #parent_user = skyfire_sdk.models.skyfire_user.SkyfireUser(
                                id = '', 
                                username = '', 
                                email = '', 
                                is_admin = True, 
                                is_enterprise_admin = True, 
                                is_active = True, 
                                is_onboarded = True, 
                                created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                attributes = null, 
                                parent_user_id = '', 
                                stytch_user_id = '', 
                                stripe_customer_id = '', 
                                #user_organizations = [
                                    skyfire_sdk.models.user_organization.UserOrganization(
                                        id = 1.337, 
                                        user_id = '', 
                                        organization_id = '', 
                                        attributes = null, 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], 
                                #wallets = [
                                    skyfire_sdk.models.wallet.Wallet(
                                        id = '', 
                                        user_id = '', 
                                        organization_id = '', 
                                        wallet_name = '', 
                                        is_default = True, 
                                        is_smart = True, 
                                        custody_provider = 'SKYFIRE_EVERVAULT', 
                                        wallet_type = 'Sender', 
                                        network = 'polygon_testnet', 
                                        wallet_address = '', 
                                        bridge_virtual_account_id = '', 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        #organization = skyfire_sdk.models.organization.Organization(
                                            id = '', 
                                            name = '', 
                                            admin_user_id = '', 
                                            created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                            updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ), )
                                    ], 
                                #default_wallet = , 
                                #organization_wallets = [
                                    
                                    ], 
                                #created_organizations = [
                                    skyfire_sdk.models.organization.Organization(
                                        id = '', 
                                        name = '', 
                                        admin_user_id = '', 
                                        created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                        updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                    ], ), 
                            #user_organizations = [
                                skyfire_sdk.models.user_organization.UserOrganization(
                                    id = 1.337, 
                                    user_id = '', 
                                    organization_id = '', 
                                    attributes = null, 
                                    created_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                    updated_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                                ], 
                            #wallets = [
                                
                                ], 
                            #default_wallet = , 
                            #organization_wallets = [
                                
                                ], 
                            #created_organizations = [
                                
                                ], ), 
                        #organization = , )
                    ],
        )
        """

    def testOrganizationResponse(self):
        """Test OrganizationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
