# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.identity_check_type import IdentityCheckType

class TestIdentityCheckType(unittest.TestCase):
    """IdentityCheckType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testIdentityCheckType(self):
        """Test IdentityCheckType"""
        # inst = IdentityCheckType()

if __name__ == '__main__':
    unittest.main()
