# coding: utf-8

"""
    Skyfire API

    The Skyfire API is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.api.api_ninja_api import APINinjaApi


class TestAPINinjaApi(unittest.TestCase):
    """APINinjaApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APINinjaApi()

    def tearDown(self) -> None:
        pass

    def test_crypto_price(self) -> None:
        """Test case for crypto_price

        Crypto Price
        """
        pass

    def test_dns_lookup(self) -> None:
        """Test case for dns_lookup

        DNS Lookup
        """
        pass

    def test_ip_lookup(self) -> None:
        """Test case for ip_lookup

        IP Lookup
        """
        pass

    def test_stock_price(self) -> None:
        """Test case for stock_price

        Stock Price
        """
        pass

    def test_weather(self) -> None:
        """Test case for weather

        Weather
        """
        pass


if __name__ == '__main__':
    unittest.main()
