# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.venice_create_chat_completion_response_choices_inner import VeniceCreateChatCompletionResponseChoicesInner

class TestVeniceCreateChatCompletionResponseChoicesInner(unittest.TestCase):
    """VeniceCreateChatCompletionResponseChoicesInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VeniceCreateChatCompletionResponseChoicesInner:
        """Test VeniceCreateChatCompletionResponseChoicesInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VeniceCreateChatCompletionResponseChoicesInner`
        """
        model = VeniceCreateChatCompletionResponseChoicesInner()
        if include_optional:
            return VeniceCreateChatCompletionResponseChoicesInner(
                finish_reason = 'stop',
                index = 56,
                message = skyfire_sdk.models.chat_completion_response_message.ChatCompletionResponseMessage(
                    content = '', 
                    tool_calls = [
                        skyfire_sdk.models.chat_completion_message_tool_call.ChatCompletionMessageToolCall(
                            id = '', 
                            type = 'function', 
                            function = skyfire_sdk.models.chat_completion_message_tool_call_function.ChatCompletionMessageToolCall_function(
                                name = '', 
                                arguments = '', ), )
                        ], 
                    role = 'assistant', 
                    function_call = skyfire_sdk.models.chat_completion_response_message_function_call.ChatCompletionResponseMessage_function_call(
                        arguments = '', 
                        name = '', ), )
            )
        else:
            return VeniceCreateChatCompletionResponseChoicesInner(
                finish_reason = 'stop',
                index = 56,
                message = skyfire_sdk.models.chat_completion_response_message.ChatCompletionResponseMessage(
                    content = '', 
                    tool_calls = [
                        skyfire_sdk.models.chat_completion_message_tool_call.ChatCompletionMessageToolCall(
                            id = '', 
                            type = 'function', 
                            function = skyfire_sdk.models.chat_completion_message_tool_call_function.ChatCompletionMessageToolCall_function(
                                name = '', 
                                arguments = '', ), )
                        ], 
                    role = 'assistant', 
                    function_call = skyfire_sdk.models.chat_completion_response_message_function_call.ChatCompletionResponseMessage_function_call(
                        arguments = '', 
                        name = '', ), ),
        )
        """

    def testVeniceCreateChatCompletionResponseChoicesInner(self):
        """Test VeniceCreateChatCompletionResponseChoicesInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
