# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.reloadly_gift_card_api_request_params_send_email import ReloadlyGiftCardAPIRequestParamsSendEmail

class TestReloadlyGiftCardAPIRequestParamsSendEmail(unittest.TestCase):
    """ReloadlyGiftCardAPIRequestParamsSendEmail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReloadlyGiftCardAPIRequestParamsSendEmail:
        """Test ReloadlyGiftCardAPIRequestParamsSendEmail
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReloadlyGiftCardAPIRequestParamsSendEmail`
        """
        model = ReloadlyGiftCardAPIRequestParamsSendEmail()
        if include_optional:
            return ReloadlyGiftCardAPIRequestParamsSendEmail(
            )
        else:
            return ReloadlyGiftCardAPIRequestParamsSendEmail(
        )
        """

    def testReloadlyGiftCardAPIRequestParamsSendEmail(self):
        """Test ReloadlyGiftCardAPIRequestParamsSendEmail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
