# coding: utf-8

"""
    Skyfire SDK

    The Skyfire SDK is designed to allow agents to interact with the Skyfire platform to enable autonomous payments.

    The version of the OpenAPI document: 1.0.0
    Contact: support@skyfire.xyz
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from skyfire_sdk.models.vetric_instagram_location_map_response_pins_inner_preview_medias_inner import VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner

class TestVetricInstagramLocationMapResponsePinsInnerPreviewMediasInner(unittest.TestCase):
    """VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner:
        """Test VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner`
        """
        model = VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner()
        if include_optional:
            return VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner(
                media_id = '',
                media_fbid = '',
                thumbnail_url = ''
            )
        else:
            return VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner(
        )
        """

    def testVetricInstagramLocationMapResponsePinsInnerPreviewMediasInner(self):
        """Test VetricInstagramLocationMapResponsePinsInnerPreviewMediasInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
