"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.edb.v1.arc_data_pb2
import ansys.api.edb.v1.point_data_pb2
import google.protobuf.wrappers_pb2
import grpc

class ArcDataServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    GetHeight: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        google.protobuf.wrappers_pb2.FloatValue] = ...
    """Get height of an arc"""

    GetCenter: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        ansys.api.edb.v1.point_data_pb2.PointMessage] = ...
    """Get center point of an arc"""

    GetMidpoint: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        ansys.api.edb.v1.point_data_pb2.PointMessage] = ...
    """Get midpoint of an arc"""

    GetRadius: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        google.protobuf.wrappers_pb2.FloatValue] = ...
    """Get radius of an arc"""

    GetBoundingBox: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        ansys.api.edb.v1.point_data_pb2.BoxMessage] = ...
    """Get bounding box of an arc"""

    GetAngle: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        google.protobuf.wrappers_pb2.FloatValue] = ...
    """Get angle between two arcs."""

    ClosestPoints: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.arc_data_pb2.ArcDataTwoArcsMessage,
        ansys.api.edb.v1.point_data_pb2.BoxMessage] = ...
    """Get closest points between two arcs."""


class ArcDataServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def GetHeight(self,
        request: ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.wrappers_pb2.FloatValue:
        """Get height of an arc"""
        pass

    @abc.abstractmethod
    def GetCenter(self,
        request: ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.point_data_pb2.PointMessage:
        """Get center point of an arc"""
        pass

    @abc.abstractmethod
    def GetMidpoint(self,
        request: ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.point_data_pb2.PointMessage:
        """Get midpoint of an arc"""
        pass

    @abc.abstractmethod
    def GetRadius(self,
        request: ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.wrappers_pb2.FloatValue:
        """Get radius of an arc"""
        pass

    @abc.abstractmethod
    def GetBoundingBox(self,
        request: ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.point_data_pb2.BoxMessage:
        """Get bounding box of an arc"""
        pass

    @abc.abstractmethod
    def GetAngle(self,
        request: ansys.api.edb.v1.arc_data_pb2.ArcMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.wrappers_pb2.FloatValue:
        """Get angle between two arcs."""
        pass

    @abc.abstractmethod
    def ClosestPoints(self,
        request: ansys.api.edb.v1.arc_data_pb2.ArcDataTwoArcsMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.point_data_pb2.BoxMessage:
        """Get closest points between two arcs."""
        pass


def add_ArcDataServiceServicer_to_server(servicer: ArcDataServiceServicer, server: grpc.Server) -> None: ...
