"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.edb.v1.edb_messages_pb2
import google.protobuf.empty_pb2
import grpc

class ICComponentPropertyServiceStub:
    """IC Component Property service definition"""
    def __init__(self, channel: grpc.Channel) -> None: ...
    Create: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...
    """Create IC Component Property"""

    SetSolderBallProperty: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Get/Set the solder ball property"""

    GetSolderBallProperty: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...

    SetDieProperty: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Get/Set the die property"""

    GetDieProperty: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...

    SetPortProperty: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Get/Set the port property"""

    GetPortProperty: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...


class ICComponentPropertyServiceServicer(metaclass=abc.ABCMeta):
    """IC Component Property service definition"""
    @abc.abstractmethod
    def Create(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage:
        """Create IC Component Property"""
        pass

    @abc.abstractmethod
    def SetSolderBallProperty(self,
        request: ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Get/Set the solder ball property"""
        pass

    @abc.abstractmethod
    def GetSolderBallProperty(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...

    @abc.abstractmethod
    def SetDieProperty(self,
        request: ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Get/Set the die property"""
        pass

    @abc.abstractmethod
    def GetDieProperty(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...

    @abc.abstractmethod
    def SetPortProperty(self,
        request: ansys.api.edb.v1.edb_messages_pb2.PointerPropertyMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Get/Set the port property"""
        pass

    @abc.abstractmethod
    def GetPortProperty(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...


def add_ICComponentPropertyServiceServicer_to_server(servicer: ICComponentPropertyServiceServicer, server: grpc.Server) -> None: ...
