"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.edb.v1.edb_messages_pb2
import ansys.api.edb.v1.padstack_inst_term_pb2
import google.protobuf.empty_pb2
import grpc

class PadstackInstanceTerminalServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Create: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.padstack_inst_term_pb2.PadstackInstTermCreationsMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...

    GetParameters: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.padstack_inst_term_pb2.PadstackInstTermParamsMessage] = ...

    SetParameters: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.padstack_inst_term_pb2.PadstackInstTermSetParamsMessage,
        google.protobuf.empty_pb2.Empty] = ...


class PadstackInstanceTerminalServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Create(self,
        request: ansys.api.edb.v1.padstack_inst_term_pb2.PadstackInstTermCreationsMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...

    @abc.abstractmethod
    def GetParameters(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.padstack_inst_term_pb2.PadstackInstTermParamsMessage: ...

    @abc.abstractmethod
    def SetParameters(self,
        request: ansys.api.edb.v1.padstack_inst_term_pb2.PadstackInstTermSetParamsMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty: ...


def add_PadstackInstanceTerminalServiceServicer_to_server(servicer: PadstackInstanceTerminalServiceServicer, server: grpc.Server) -> None: ...
