"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import ansys.api.edb.v1.edb_messages_pb2
import ansys.api.edb.v1.path_pb2
import ansys.api.edb.v1.polygon_data_pb2
import google.protobuf.empty_pb2
import grpc

class PathServiceStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    Create: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.PathCreationMessage,
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage] = ...

    Render: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.PathRenderMessage,
        ansys.api.edb.v1.polygon_data_pb2.PolygonDataMessage] = ...
    """Render Path"""

    GetPolygonData: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.polygon_data_pb2.PolygonDataMessage] = ...
    """Get Polygon Data"""

    GetCenterLine: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.polygon_data_pb2.PolygonDataMessage] = ...
    """Get Center Line"""

    SetCenterLine: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.SetCenterLineMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Set Center Line"""

    GetEndCapStyle: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.path_pb2.EndCapStyleMessage] = ...
    """Get End Cap Style"""

    SetEndCapStyle: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.SetEndCapStyleMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Set End Cap Style"""

    GetClipInfo: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.path_pb2.ClipInfoMessage] = ...
    """Get Clip Info"""

    SetClipInfo: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.SetClipInfoMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Set Clip Info"""

    GetCornerStyle: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.path_pb2.CornerStyleMessage] = ...
    """Get Corner Style"""

    SetCornerStyle: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.SetCornerStyleMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Set Corner Style"""

    GetWidth: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.path_pb2.WidthMessage] = ...
    """Get Width"""

    SetWidth: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.SetWidthMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Set Width"""

    GetMiterRatio: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        ansys.api.edb.v1.path_pb2.MiterRatioMessage] = ...
    """Get Miter Ratio"""

    SetMiterRatio: grpc.UnaryUnaryMultiCallable[
        ansys.api.edb.v1.path_pb2.SetMiterRatioMessage,
        google.protobuf.empty_pb2.Empty] = ...
    """Set Miter Ratio"""


class PathServiceServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def Create(self,
        request: ansys.api.edb.v1.path_pb2.PathCreationMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage: ...

    @abc.abstractmethod
    def Render(self,
        request: ansys.api.edb.v1.path_pb2.PathRenderMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.polygon_data_pb2.PolygonDataMessage:
        """Render Path"""
        pass

    @abc.abstractmethod
    def GetPolygonData(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.polygon_data_pb2.PolygonDataMessage:
        """Get Polygon Data"""
        pass

    @abc.abstractmethod
    def GetCenterLine(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.polygon_data_pb2.PolygonDataMessage:
        """Get Center Line"""
        pass

    @abc.abstractmethod
    def SetCenterLine(self,
        request: ansys.api.edb.v1.path_pb2.SetCenterLineMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Set Center Line"""
        pass

    @abc.abstractmethod
    def GetEndCapStyle(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.path_pb2.EndCapStyleMessage:
        """Get End Cap Style"""
        pass

    @abc.abstractmethod
    def SetEndCapStyle(self,
        request: ansys.api.edb.v1.path_pb2.SetEndCapStyleMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Set End Cap Style"""
        pass

    @abc.abstractmethod
    def GetClipInfo(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.path_pb2.ClipInfoMessage:
        """Get Clip Info"""
        pass

    @abc.abstractmethod
    def SetClipInfo(self,
        request: ansys.api.edb.v1.path_pb2.SetClipInfoMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Set Clip Info"""
        pass

    @abc.abstractmethod
    def GetCornerStyle(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.path_pb2.CornerStyleMessage:
        """Get Corner Style"""
        pass

    @abc.abstractmethod
    def SetCornerStyle(self,
        request: ansys.api.edb.v1.path_pb2.SetCornerStyleMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Set Corner Style"""
        pass

    @abc.abstractmethod
    def GetWidth(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.path_pb2.WidthMessage:
        """Get Width"""
        pass

    @abc.abstractmethod
    def SetWidth(self,
        request: ansys.api.edb.v1.path_pb2.SetWidthMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Set Width"""
        pass

    @abc.abstractmethod
    def GetMiterRatio(self,
        request: ansys.api.edb.v1.edb_messages_pb2.EDBObjMessage,
        context: grpc.ServicerContext,
    ) -> ansys.api.edb.v1.path_pb2.MiterRatioMessage:
        """Get Miter Ratio"""
        pass

    @abc.abstractmethod
    def SetMiterRatio(self,
        request: ansys.api.edb.v1.path_pb2.SetMiterRatioMessage,
        context: grpc.ServicerContext,
    ) -> google.protobuf.empty_pb2.Empty:
        """Set Miter Ratio"""
        pass


def add_PathServiceServicer_to_server(servicer: PathServiceServicer, server: grpc.Server) -> None: ...
