import amsdal_glue as glue
from typing import Any

def split_conditions(conditions: glue.Conditions | glue.Condition) -> list[glue.Conditions]: ...
def pull_out_filter_from_query(conditions: glue.Conditions, field: glue.Field) -> tuple[set[Any], glue.Conditions | None]: ...
def sort_items(items: list[glue.Data], order_by_list: list[glue.OrderByQuery] | None) -> list[glue.Data]: ...
def get_field_value(item: dict[str, Any], field: glue.Field) -> Any: ...
def _process_and_split(conditions: glue.Conditions) -> list[glue.Conditions]: ...
def _process_or_split(conditions: glue.Conditions) -> list[glue.Conditions]: ...
def _reverse_conditions(conditions: glue.Conditions) -> glue.Conditions: ...
