import eyed3
import magic
from _typeshed import Incomplete
from eyed3.mimetype import guessMimetype as guessMimetype

class MagicTypes(magic.Magic):
    def __init__(self) -> None: ...
    def guess_type(self, filename, all_types: bool = False): ...

class MimetypesPlugin(eyed3.plugins.LoaderPlugin):
    NAMES: Incomplete
    magic: Incomplete
    start_t: Incomplete
    mime_types: Incomplete
    def __init__(self, arg_parser) -> None: ...
    def start(self, args, config) -> None: ...
    def handleFile(self, f, *args, **kwargs) -> None: ...
    def handleDone(self) -> None: ...
