
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-04T08:55:36-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9ee7c9dbf93b829c65f3331bc1a04c1474e8a32",
 "version": "0.29.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
