# coding: utf-8

"""
    Hitobito JSON:API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: oss@basilbader.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PeopleReadableAttribute(str, Enum):
    """
    Person readable attributes
    """

    """
    allowed enum values
    """
    ID = 'id'
    FIRST_NAME = 'first_name'
    LAST_NAME = 'last_name'
    NICKNAME = 'nickname'
    COMPANY_NAME = 'company_name'
    COMPANY = 'company'
    EMAIL = 'email'
    ADDRESS = 'address'
    ZIP_CODE = 'zip_code'
    TOWN = 'town'
    COUNTRY = 'country'
    PRIMARY_GROUP_ID = 'primary_group_id'
    GENDER = 'gender'
    BIRTHDAY = 'birthday'
    LANGUAGE = 'language'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PeopleReadableAttribute from a JSON string"""
        return cls(json.loads(json_str))


