from _typeshed import Incomplete
from pathlib import Path
from ycf.cli import settings as settings

logger: Incomplete

class BaseSource:
    def __init__(self) -> None: ...
    @property
    def release_version(self) -> str: ...
    @property
    def release_name(self) -> str: ...
    @property
    def release_zip_name(self) -> str: ...
    @property
    def release_zip_path(self) -> Path: ...
    @property
    def include_files(self) -> set[str]: ...
    @property
    def include_tmp_files(self) -> dict[str, str]: ...
    def build(self) -> None: ...
