
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-03T15:32:40-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b1c16c1d94c6ae95693a5eabc847a3fecb5d6fa3",
 "version": "2025.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
