"""

imfusion.machinelearning - Bindings for Machine Learning
==========================================================

This submodule provides Python bindings for the C++ ImFusion classes that can be used during the training of machine learning models.
"""
from __future__ import annotations
import abc as abc
import imfusion as imfusion
from imfusion.machinelearning._bindings import AddCenterBoxOperation
from imfusion.machinelearning._bindings import AddDegradedLabelAsChannelOperation
from imfusion.machinelearning._bindings import AddPixelwisePredictionChannelOperation
from imfusion.machinelearning._bindings import AddPositionChannelOperation
from imfusion.machinelearning._bindings import AddRandomNoiseOperation
from imfusion.machinelearning._bindings import AdjustShiftScaleOperation
from imfusion.machinelearning._bindings import ApplyTopDownFlagOperation
from imfusion.machinelearning._bindings import ApproximateToHigherResolutionOperation
from imfusion.machinelearning._bindings import ArgMaxOperation
from imfusion.machinelearning._bindings import AxisFlipOperation
from imfusion.machinelearning._bindings import AxisRotationOperation
from imfusion.machinelearning._bindings import BakeDeformationOperation
from imfusion.machinelearning._bindings import BakePhotometricInterpretationOperation
from imfusion.machinelearning._bindings import BakeTransformationOperation
from imfusion.machinelearning._bindings import BlobsFromKeypointsOperation
from imfusion.machinelearning._bindings import BoundingBoxElement
from imfusion.machinelearning._bindings import BoundingBoxSet
from imfusion.machinelearning._bindings import Box
from imfusion.machinelearning._bindings import CenterROISampler
from imfusion.machinelearning._bindings import CheckDataOperation
from imfusion.machinelearning._bindings import ClipOperation
from imfusion.machinelearning._bindings import ComputingDevice
from imfusion.machinelearning._bindings import ConcatenateNeighboringFramesToChannelsOperation
from imfusion.machinelearning._bindings import ConvertSlicesToVolumeOperation
from imfusion.machinelearning._bindings import ConvertToGrayOperation
from imfusion.machinelearning._bindings import ConvertVolumeToSlicesOperation
from imfusion.machinelearning._bindings import ConvolutionalCRFOperation
from imfusion.machinelearning._bindings import CopyOperation
from imfusion.machinelearning._bindings import CropAroundLabelMapOperation
from imfusion.machinelearning._bindings import CropOperation
from imfusion.machinelearning._bindings import CutOutOperation
from imfusion.machinelearning._bindings import DataElement
from imfusion.machinelearning._bindings import DataElementException
from imfusion.machinelearning._bindings import DataItem
from imfusion.machinelearning._bindings import DataItemException
from imfusion.machinelearning._bindings import DataLoaderError
from imfusion.machinelearning._bindings import DataLoaderSpecs
from imfusion.machinelearning._bindings import Dataset
from imfusion.machinelearning._bindings import DefaultROISampler
from imfusion.machinelearning._bindings import DeformationOperation
from imfusion.machinelearning._bindings import DiceMetric
from imfusion.machinelearning._bindings import ElementType
from imfusion.machinelearning._bindings import Engine
from imfusion.machinelearning._bindings import EngineConfiguration
from imfusion.machinelearning._bindings import EnsureExplicitMaskOperation
from imfusion.machinelearning._bindings import EnsureOneToOneMatrixMappingOperation
from imfusion.machinelearning._bindings import ExecutionProvider
from imfusion.machinelearning._bindings import ExtractRandomSubsetOperation
from imfusion.machinelearning._bindings import ExtractSubsetOperation
from imfusion.machinelearning._bindings import ForegroundGuidedLabelUpsamplingOperation
from imfusion.machinelearning._bindings import GammaCorrectionOperation
from imfusion.machinelearning._bindings import HighPassOperation
from imfusion.machinelearning._bindings import ImageElement
from imfusion.machinelearning._bindings import ImageMattingOperation
from imfusion.machinelearning._bindings import ImageROISampler
from imfusion.machinelearning._bindings import ImageSamplerError
from imfusion.machinelearning._bindings import ImagewiseClassificationMetrics
from imfusion.machinelearning._bindings import InterleaveMode
from imfusion.machinelearning._bindings import InvertOperation
from imfusion.machinelearning._bindings import KeepLargestComponentOperation
from imfusion.machinelearning._bindings import KeypointSet
from imfusion.machinelearning._bindings import KeypointsElement
from imfusion.machinelearning._bindings import KeypointsFromBlobsOperation
from imfusion.machinelearning._bindings import LabelROISampler
from imfusion.machinelearning._bindings import LinearIntensityMappingOperation
from imfusion.machinelearning._bindings import MRIBiasFieldCorrectionOperation
from imfusion.machinelearning._bindings import MRIBiasFieldGenerationOperation
from imfusion.machinelearning._bindings import MachineLearningModel
from imfusion.machinelearning._bindings import MakeFloatOperation
from imfusion.machinelearning._bindings import MarkAsTargetOperation
from imfusion.machinelearning._bindings import MergeAsChannelsOperation
from imfusion.machinelearning._bindings import Metric
from imfusion.machinelearning._bindings import MetricException
from imfusion.machinelearning._bindings import ModelType
from imfusion.machinelearning._bindings import MorphologicalFilterOperation
from imfusion.machinelearning._bindings import NormalizeMADOperation
from imfusion.machinelearning._bindings import NormalizeNormalOperation
from imfusion.machinelearning._bindings import NormalizePercentileOperation
from imfusion.machinelearning._bindings import NormalizeUniformOperation
from imfusion.machinelearning._bindings import OneHotOperation
from imfusion.machinelearning._bindings import Operation
from imfusion.machinelearning._bindings import OperationError
from imfusion.machinelearning._bindings import OperationsSequence
from imfusion.machinelearning._bindings import OrientedROISampler
from imfusion.machinelearning._bindings import PadDimsOperation
from imfusion.machinelearning._bindings import PadOperation
from imfusion.machinelearning._bindings import ParamUnit
from imfusion.machinelearning._bindings import Phase
from imfusion.machinelearning._bindings import PixelwiseClassificationMetrics
from imfusion.machinelearning._bindings import PolyCropOperation
from imfusion.machinelearning._bindings import PredictionOutput
from imfusion.machinelearning._bindings import PredictionType
from imfusion.machinelearning._bindings import ProcessingRecordComponent
from imfusion.machinelearning._bindings import RandomAddDegradedLabelAsChannelOperation
from imfusion.machinelearning._bindings import RandomAddRandomNoiseOperation
from imfusion.machinelearning._bindings import RandomAxisFlipOperation
from imfusion.machinelearning._bindings import RandomAxisRotationOperation
from imfusion.machinelearning._bindings import RandomChoiceOperation
from imfusion.machinelearning._bindings import RandomCropAroundLabelMapOperation
from imfusion.machinelearning._bindings import RandomCropOperation
from imfusion.machinelearning._bindings import RandomCutOutOperation
from imfusion.machinelearning._bindings import RandomDeformationOperation
from imfusion.machinelearning._bindings import RandomGammaCorrectionOperation
from imfusion.machinelearning._bindings import RandomImageFromLabelOperation
from imfusion.machinelearning._bindings import RandomInvertOperation
from imfusion.machinelearning._bindings import RandomKeypointJitterOperation
from imfusion.machinelearning._bindings import RandomLinearIntensityMappingOperation
from imfusion.machinelearning._bindings import RandomMRIBiasFieldGenerationOperation
from imfusion.machinelearning._bindings import RandomPolyCropOperation
from imfusion.machinelearning._bindings import RandomROISampler
from imfusion.machinelearning._bindings import RandomResolutionReductionOperation
from imfusion.machinelearning._bindings import RandomRotationOperation
from imfusion.machinelearning._bindings import RandomScalingOperation
from imfusion.machinelearning._bindings import RandomSmoothOperation
from imfusion.machinelearning._bindings import RandomTemplateInpaintingOperation
from imfusion.machinelearning._bindings import RectifyRotationOperation
from imfusion.machinelearning._bindings import RemoveMaskOperation
from imfusion.machinelearning._bindings import RemoveOperation
from imfusion.machinelearning._bindings import RenameOperation
from imfusion.machinelearning._bindings import ReplaceLabelsValuesOperation
from imfusion.machinelearning._bindings import ResampleDimsOperation
from imfusion.machinelearning._bindings import ResampleKeepingAspectRatioOperation
from imfusion.machinelearning._bindings import ResampleOperation
from imfusion.machinelearning._bindings import ResampleToInputOperation
from imfusion.machinelearning._bindings import ResetCriterion
from imfusion.machinelearning._bindings import ResolutionReductionOperation
from imfusion.machinelearning._bindings import RotationOperation
from imfusion.machinelearning._bindings import RunModelOperation
from imfusion.machinelearning._bindings import SISBasedElement
from imfusion.machinelearning._bindings import ScalingOperation
from imfusion.machinelearning._bindings import SelectChannelsOperation
from imfusion.machinelearning._bindings import SetLabelModalityOperation
from imfusion.machinelearning._bindings import SetMatrixToIdentityOperation
from imfusion.machinelearning._bindings import SetModalityOperation
from imfusion.machinelearning._bindings import SetSpacingOperation
from imfusion.machinelearning._bindings import SigmoidOperation
from imfusion.machinelearning._bindings import SmoothOperation
from imfusion.machinelearning._bindings import SoftmaxOperation
from imfusion.machinelearning._bindings import SplitROISampler
from imfusion.machinelearning._bindings import SurfaceDistancesMetric
from imfusion.machinelearning._bindings import SwapImageAndLabelsOperation
from imfusion.machinelearning._bindings import SyncOperation
from imfusion.machinelearning._bindings import TanhOperation
from imfusion.machinelearning._bindings import TargetTag
from imfusion.machinelearning._bindings import TemplateInpaintingOperation
from imfusion.machinelearning._bindings import Tensor
from imfusion.machinelearning._bindings import TensorElement
from imfusion.machinelearning._bindings import ThresholdOperation
from imfusion.machinelearning._bindings import UnmarkAsTargetOperation
from imfusion.machinelearning._bindings import VectorElement
from imfusion.machinelearning._bindings import available_cpp_engines
from imfusion.machinelearning._bindings import available_engines
from imfusion.machinelearning._bindings import available_py_engines
from imfusion.machinelearning._bindings import is_semantic_segmentation_map
from imfusion.machinelearning._bindings import is_target
from imfusion.machinelearning._bindings import propertylist_to_data_loader_specs
from imfusion.machinelearning._bindings import register_filter_func
from imfusion.machinelearning._bindings import register_map_func
from imfusion.machinelearning._bindings import register_py_op_cls
from imfusion.machinelearning._bindings import tag_as_target
from imfusion.machinelearning._bindings import untag_as_target
from imfusion.machinelearning.engines import LazyModule
from imfusion.machinelearning.torch_utils import to_torch
import platform as platform
import sys as sys
from . import _bindings
from . import engines
from . import torch_utils
__all__ = ['AbstractOperation', 'AddCenterBoxOperation', 'AddDegradedLabelAsChannelOperation', 'AddPixelwisePredictionChannelOperation', 'AddPositionChannelOperation', 'AddRandomNoiseOperation', 'AdjustShiftScaleOperation', 'ApplyTopDownFlagOperation', 'ApproximateToHigherResolutionOperation', 'ArgMaxOperation', 'AxisFlipOperation', 'AxisRotationOperation', 'BakeDeformationOperation', 'BakePhotometricInterpretationOperation', 'BakeTransformationOperation', 'BlobsFromKeypointsOperation', 'BoundingBoxElement', 'BoundingBoxSet', 'Box', 'CenterROISampler', 'CheckDataOperation', 'ClipOperation', 'ComputingDevice', 'ConcatenateNeighboringFramesToChannelsOperation', 'ConvertSlicesToVolumeOperation', 'ConvertToGrayOperation', 'ConvertVolumeToSlicesOperation', 'ConvolutionalCRFOperation', 'CopyOperation', 'CropAroundLabelMapOperation', 'CropOperation', 'CutOutOperation', 'DataElement', 'DataElementException', 'DataItem', 'DataItemException', 'DataLoaderError', 'DataLoaderSpecs', 'Dataset', 'DefaultROISampler', 'DeformationOperation', 'DiceMetric', 'ElementType', 'Engine', 'EngineConfiguration', 'EnsureExplicitMaskOperation', 'EnsureOneToOneMatrixMappingOperation', 'ExecutionProvider', 'ExtractRandomSubsetOperation', 'ExtractSubsetOperation', 'ForegroundGuidedLabelUpsamplingOperation', 'GammaCorrectionOperation', 'HighPassOperation', 'ImageElement', 'ImageMattingOperation', 'ImageROISampler', 'ImageSamplerError', 'ImagewiseClassificationMetrics', 'InterleaveMode', 'InvertOperation', 'KeepLargestComponentOperation', 'KeypointSet', 'KeypointsElement', 'KeypointsFromBlobsOperation', 'LabelROISampler', 'LazyModule', 'LinearIntensityMappingOperation', 'MRIBiasFieldCorrectionOperation', 'MRIBiasFieldGenerationOperation', 'MachineLearningModel', 'MakeFloatOperation', 'MarkAsTargetOperation', 'MergeAsChannelsOperation', 'Metric', 'MetricException', 'ModelType', 'MorphologicalFilterOperation', 'NormalizeMADOperation', 'NormalizeNormalOperation', 'NormalizePercentileOperation', 'NormalizeUniformOperation', 'OneHotOperation', 'Operation', 'OperationError', 'OperationsSequence', 'OrientedROISampler', 'PadDimsOperation', 'PadOperation', 'ParamUnit', 'Phase', 'PixelwiseClassificationMetrics', 'PolyCropOperation', 'PredictionOutput', 'PredictionType', 'ProcessingRecordComponent', 'RandomAddDegradedLabelAsChannelOperation', 'RandomAddRandomNoiseOperation', 'RandomAxisFlipOperation', 'RandomAxisRotationOperation', 'RandomChoiceOperation', 'RandomCropAroundLabelMapOperation', 'RandomCropOperation', 'RandomCutOutOperation', 'RandomDeformationOperation', 'RandomGammaCorrectionOperation', 'RandomImageFromLabelOperation', 'RandomInvertOperation', 'RandomKeypointJitterOperation', 'RandomLinearIntensityMappingOperation', 'RandomMRIBiasFieldGenerationOperation', 'RandomPolyCropOperation', 'RandomROISampler', 'RandomResolutionReductionOperation', 'RandomRotationOperation', 'RandomScalingOperation', 'RandomSmoothOperation', 'RandomTemplateInpaintingOperation', 'RectifyRotationOperation', 'RemoveMaskOperation', 'RemoveOperation', 'RenameOperation', 'ReplaceLabelsValuesOperation', 'ResampleDimsOperation', 'ResampleKeepingAspectRatioOperation', 'ResampleOperation', 'ResampleToInputOperation', 'ResetCriterion', 'ResolutionReductionOperation', 'RotationOperation', 'RunModelOperation', 'SISBasedElement', 'ScalingOperation', 'SelectChannelsOperation', 'SetLabelModalityOperation', 'SetMatrixToIdentityOperation', 'SetModalityOperation', 'SetSpacingOperation', 'SigmoidOperation', 'SmoothOperation', 'SoftmaxOperation', 'SplitROISampler', 'SurfaceDistancesMetric', 'SwapImageAndLabelsOperation', 'SyncOperation', 'TanhOperation', 'TargetTag', 'TemplateInpaintingOperation', 'Tensor', 'TensorElement', 'ThresholdOperation', 'UnmarkAsTargetOperation', 'VectorElement', 'abc', 'available_cpp_engines', 'available_engines', 'available_py_engines', 'engines', 'imfusion', 'is_semantic_segmentation_map', 'is_target', 'platform', 'propertylist_to_data_loader_specs', 'register_filter_func', 'register_map_func', 'register_py_op_cls', 'sys', 'tag_as_target', 'to_torch', 'torch_utils', 'untag_as_target']
class AbstractOperation(_bindings.Operation):
    def __init__(self, name = '', processing_policy = ...):
        ...
    def __init_subclass__(self, *args, **kwargs):
        ...
def __DataElement_array(self: _bindings.DataElement, copy = False):
    ...
def __DataElement_iter(self) -> typing.Iterator:
    ...
