import random

FLIRTY_LINES = [
    "Are you a magician? Because whenever I look at you, everyone else disappears.✨",
    "Do you believe in love at first sight, or should I walk by again?😉",
    "Are you French? Because Eiffel for you.❤️",
    "You must be made of copper and tellurium because you're Cu-Te.😍",
    "Do you like Star Wars? Because Yoda one for me.💫",
    "Is your name Google? Because you have everything I've been searching for.🔍",
       "I must be in a museum, because you truly are a work of art.",
    "Did it hurt when you fell from heaven?",
    "Is your name Google? Because you have everything I’ve been searching for.",
    "I’m not a photographer, but I can picture us together.",
    "Your smile must be a black hole—nothing can escape its pull.",
    "Do you have a map? I keep getting lost in your eyes.",
    "Are you a parking ticket? Because you’ve got FINE written all over you.",
    "I must be a snowflake, because I’ve fallen for you.",
    "You must be tired, because you’ve been running through my mind all day.",
    "Is your name WiFi? Because I’m feeling a strong connection.",
    "Do you believe in fate? Because I think we’ve just made a connection.",
    "Your hand looks heavy—can I hold it for you?",
    "Is there a rainbow today? Because I just found my treasure.",
    "Are you a magician? Every time I look at you, everyone else disappears.",
    "You must be made of stardust, because you’re out of this world.",
    "My phone seems broken—it doesn’t have your number in it.",
    "If beauty were a crime, you'd be on the FBI's most wanted list.",
    "Is your dad a boxer? Because you’re a knockout.",
    "If I had a star for every time you brightened my day, I’d have a galaxy.",
    "I was feeling a little off today, but you definitely turned me on.",
    "If kisses were snowflakes, I’d send you a blizzard.",
    "I’m learning about important dates in history—wanna be one of them?",
    "If looks could kill, you’d be a weapon of mass destruction.",
    "Your eyes are so captivating, I forgot my pickup line.",
    "You’re so sweet, you could put Hershey’s out of business.",
    "Are you a campfire? Because you’re hot and I want s’more.",
    "Do you have a Band-Aid? I just scraped my knee falling for you.",
    "Are you a bank loan? Because you’ve got my interest.",
    "Can I follow you home? Because my parents always told me to follow my dreams.",
    "Your beauty blinded me; I’m going to need your name and number for insurance purposes.",
    "You must be a keyboard, because you’re just my type.",
    "If you were a triangle, you’d be acute one.",
    "I’m not a genie, but I can make your dreams come true.",
    "If I could rearrange the alphabet, I’d put U and I together.",
    "Are you Netflix? Because I could watch you for hours.",
    "I’m new in town; can you give me directions to your heart?",
    "Are you a time traveler? Because I can see you in my future.",
    "Do you have any raisins? No? How about a date?",
    "Your lips look lonely—would they like to meet mine?",
    "Is your nickname Chapstick? Because you’re da balm.",
    "Are you an electrician? Because you’re lighting up my day.",
    "I must be lost, because heaven is a long way from here.",
    "You must be a broom, because you just swept me off my feet.",
    "They say Disneyland is the happiest place on Earth—apparently, no one’s ever stood next to you.",
    "Do you have a sunburn, or are you always this hot?",
    "You might be asked to leave soon—you’re making the other women look bad.",
    "I had a clever line, but you’re so stunning I forgot it.",
    "Is there an airport nearby, or is that just my heart taking off?",
    "Your eyes are like the ocean; I could swim in them all day.",
    "If I had a garden, I’d put your tulips and my tulips together.",
    "You’re like a dictionary—you add meaning to my life.",
    "Are you made of copper and tellurium? Because you’re Cu-Te.",
    "Are you a cat? Because I’m feline a connection between us.",
    "Do you believe in love at first sight, or should I walk by again?",
    "Your eyes are brighter than the sun, but I promise not to stare too long.",
    "Are you my phone charger? Because without you, I’d die.",
    "You’re so beautiful that I forgot my next pickup line.",
    "If you were a fruit, you’d be a fine-apple.",
    "On a scale of 1 to 10, you’re a 9—and I’m the 1 you need.",
    "Your smile must be a black hole—no matter how often I see it, I can’t escape its pull.",
    "If you were words on a page, you’d be fine print.",
    "I’m no mathematician, but I’m pretty good with numbers—tell you what, give me yours and watch what I can do with it.",
    "I thought happiness started with an H. Why does mine start with U?",
    "Kiss me if I’m wrong, but dinosaurs still exist, right?",
    "Are you related to Jean-Claude Van Damme? Because Jean-Claude Van Damme you’re sexy!",
    "You must be a magnet, because you sure are attracting me over here.",
    "You’re like a campfire—hot and I’m drawn to your warmth.",
    "You must be a shooting star, because you just made all my wishes come true.",
    "Did you swallow magnets? Because you’re attractive.",
    "I’m on a treasure hunt—can I look in your eyes for the X?",
    "Are you from Tennessee? Because you’re the only ten I see.",
    "I might need a compass because I keep getting lost in your eyes.",
    "If you were a library book, I’d check you out.",
    "If kisses were currency, I’d be a millionaire by now.",
    "I think there’s something wrong with my phone—it doesn’t have your number in it.",
    "I tried to think of a line, but all I can think of is how gorgeous you are.",
    "I think I’m reading a map—because I just got lost in your eyes.",
    "I just wanted to show this rose how incredibly beautiful you are.",
    "Is your last name Gillette? Because you’re the best a man can get.",
    "Are you a dictionary? Because I’m lost for words.",
    "I don’t need Instagram because I’m already following you.",
    "I wish I were cross-eyed so I could see you twice.",
    "Do you have a license? Because you’re driving me crazy.",
    "Are you a camera? Because every time I look at you, I smile.",
    "You’re so sweet, you could put candy shops out of business.",
    "Are you from the future? Because my future definitely includes you.",
    "You must be a wifi hotspot, because I’m feeling a strong connection.",
    "Your presence is like coffee—strong and invigorating.",
    "Your beauty is so overwhelming, the paramedics are on their way.",
    "Are you the ocean? Because I’m lost at sea.",
    "If I wrote a book about you, it would be a bestseller.",
    "You’re the reason even Santa has a naughty list.",
    "Are you an alien? Because you’ve just abducted my heart.",
    "If charm was a weapon, you’d be a mass destruction device.",
    "Your smile is like the sunrise—it brightens my day.",
    "I’m not an electrician, but I can light up your day.",
    "If you were a burger at McDonald’s, you’d be the McGorgeous.",
    "You’re the missing piece to my puzzle.",
    "I must be a light switch, because every time I see you, you turn me on.",
    "Is your name Chapstick? Because you’re da balm.",
    "Your eyes shine brighter than the stars.",
    "If I had to choose between breathing and loving you, I’d use my last breath to say I love you.",
    "Are you a parking ticket? Because you’re too fine to be true.",
    "I’d say God bless you, but it looks like he already did.",
    "I was feeling off today, but seeing you definitely turned me on.",
    "You must be a wizard, because whenever I see you, everyone else disappears.",
    "If you were a dessert, you’d be the sweetest thing on the menu.",
    "I think my heart just skipped a beat—did you feel it too?",
    "Are you a genie? Because you’re making all my wishes come true.",
    "If I could hold a star for every time you made me smile, I’d have the entire sky.",
    "If flirting was a crime, I’d be your partner in jail.",
    "I wish I was your mirror, so I could see you every morning.",
    "If I had a rose for every time I thought of you, I’d be walking in a garden forever.",
    "Are you a piece of art? Because I want to admire you all day.",
    "You must be a beaver, because daaaaam.",
    "You’re like the sun—my whole world revolves around you.",
    "Do you have a name, or can I just call you mine?",
    "If you were a potion, I’d drink every drop.",
    "I’m no mathematician, but we’re a perfect equation.",
    "You’re so captivating, I forgot how to speak.",
    "If I had a penny for every time I smiled thinking of you, I’d be a billionaire.",
    "Let’s be like a pair of socks and make a great match.",
    "I’m not an astronomer, but I think the stars revolve around you.",
    "You must be exhausted, because you’ve been running through my mind.",
    "I must be dancing with the devil, because you’re hot as hell.",
    "I’m not sure what happiness looks like until I see you.",
    "I must be a banana, because I find you a-peel-ing.",
    "Are you a light bulb? Because you brighten my day.",
    "I’d cross the galaxy just to say hello.",
    "They say the eyes are the windows to the soul—yours must be mesmerizing.",
    "Your beauty is so bright, it outshines the sun.",
    "You must be a diamond, because you shine under pressure.",
    "You’re the spark that ignites my day.",
    "My day isn’t complete unless I see your smile.",
    "I hope you know CPR, because you just took my breath away.",
    "If I were a superhero, my power would be loving you endlessly.",
    "Are you a florist? Because every time I see you, I blossom.",
    "You’re the exclamation mark in the happiest sentence I could ever write.",
    "I’m convinced your parents are bakers, because you’re a cutie pie.",
    "Life without you is like a broken pencil—pointless.",
    "I can’t spell ‘awesome’ without ‘we’.",
    "You’re my favorite daydream.",
    "I’d do anything to be the reason you smile.",
    "If you were a book, I’d never put you down.",
    "If you were a melody, I’d play you on repeat.",
    "Are you gravity? Because you keep pulling me in.",
    "You’re the reason I look forward to waking up.",
    "You must be a dictionary, because you add meaning to my life.",
    "Your beauty is so captivating, I’m speechless.",
    "If you were a coffee, you’d be espresso—strong, hot, and sweet.",
    "I could hold you forever and never get tired.",
    "Your voice is my favorite sound.",
    "Are you a candle? Because you light up my world.",
    "You’re the reason the word ‘amazing’ exists.",
    "I need a compass whenever I see you—I get lost in your eyes.",
    "You’re my personal definition of perfect.",
    "If I wrote you a song, it would be the number one hit.",
    "Your smile is the only sunshine I need.",
    "You’re like a cloud—soft, beautiful, and impossible to catch.",
    "I don’t believe in luck, but I sure feel lucky when I’m with you.",
    "Your laughter is my favorite soundtrack.",
    "I’d give up chocolate for you—and that’s saying a lot.",
    "If kisses were stars, I’d give you the Milky Way.",
    "Your name must be Autumn, because I fall for you every day.",
    "You’re the reason fairy tales exist.",
    "I’d walk a thousand miles just to see your smile.",
    "If I could rewrite the alphabet, I’d put U and I in neon lights.",
    "You make my heart race faster than a cheetah on Red Bull.",
    "Your beauty is a puzzle, and I want to spend my life solving it.",
    "If I had a time machine, I’d go back to the day we met and do it all over again.",
    "If loving you was a job, I’d be the most dedicated employee.",
    "You must be a campfire, because I’m drawn to your warmth and glow.",
    "I’d climb any mountain just to be near you.",
    "Is your heart a bakery? Because I knead you.",
    "If I had to describe you in one word, it would be ‘mine.’",
    "Your presence is like a good dream—I never want to wake up.",
    "They say home is where the heart is—can I move in with you?",
    "If I could hold time, I’d freeze every moment we’re together.",
    "You’re the reason I smile randomly.",
    "Are you a dictionary? Because I’m lost in your words.",
    "I could stare into your eyes forever and never get bored.",
    "You’re the highlight of my day.",
    "If love was a storybook, we’d meet on every page.",
    "I wish I could bottle your laugh—it’s the sweetest sound.",
    "You’re the reason the Earth keeps spinning.",
    "If you were a painting, I’d stare at you all day.",
    "They say the best things in life are free—so how can I get you?",
    "Your aura is so bright, it could outshine a full moon.",
    "If my heart was a lock, you’d have the key.",
    "Your beauty is so unique, they should name a constellation after you.",
    "If I had one wish, it would be to wake up next to you every morning.",
    "Your vibe is so contagious, I can’t help but smile.",
    "I never believed in destiny until I met you.",
    "You must be the reason love songs exist.",
    "Your face should be on a magazine cover.",
    "I think you just turned my world upside down—in the best way possible.",
    "If I had wings, I’d fly to wherever you are.",
    "You’re the reason my heart does a happy dance.",
    "I could spend a lifetime trying to describe how amazing you are.",
    "You’re my favorite thought in the morning and my sweetest dream at night."# Add at least 200 lines
]

def get_flirty_line():
    """Returns a random flirty line."""
    return random.choice(FLIRTY_LINES)
