
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-03T14:54:25+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "25a2350fcd3703b3ec2a684ed92adc7bb368ca2a",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
