__author__ = 'Eliaquim Souza, Rafael Silva, Elton Pescador'
__copyright__ = '2025-2025 eliaquimrs rafalexandre1 FishermanXD'
__email__ = 'eliaquim.rsv@gmail.com,rafael.alexandre.tm@gmail.com,eltonpescadorvieira@gmail.com'
__license__ = 'GPL-3.0'
__title__ = 'python-mantis'
__version__ = '0.6'