# coding: utf-8

"""
    Hitobito JSON:API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@hitobito.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jubladb_api.models.roles import Roles

class TestRoles(unittest.TestCase):
    """Roles unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Roles:
        """Test Roles
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Roles`
        """
        model = Roles()
        if include_optional:
            return Roles(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                start_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                end_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                person_id = 56,
                group_id = 56,
                type = '',
                label = ''
            )
        else:
            return Roles(
        )
        """

    def testRoles(self):
        """Test Roles"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
