# coding: utf-8

"""
    Hitobito JSON:API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@hitobito.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jubladb_api.models.phone_numbers_request import PhoneNumbersRequest

class TestPhoneNumbersRequest(unittest.TestCase):
    """PhoneNumbersRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PhoneNumbersRequest:
        """Test PhoneNumbersRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PhoneNumbersRequest`
        """
        model = PhoneNumbersRequest()
        if include_optional:
            return PhoneNumbersRequest(
                data = jubladb_api.models.phone_numbers_resource.phone_numbers_resource(
                    id = '58', 
                    type = 'phone_numbers', 
                    attributes = jubladb_api.models.phone_numbers.phone_numbers(
                        label = '', 
                        public = True, 
                        contactable_id = 56, 
                        contactable_type = '', 
                        number = '', ), 
                    relationships = jubladb_api.models.relationships.relationships(), 
                    links = {
                        'key' : null
                        }, )
            )
        else:
            return PhoneNumbersRequest(
        )
        """

    def testPhoneNumbersRequest(self):
        """Test PhoneNumbersRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
