# coding: utf-8

"""
    Hitobito JSON:API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@hitobito.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from jubladb_api.models.additional_emails_readable_attribute import AdditionalEmailsReadableAttribute

class TestAdditionalEmailsReadableAttribute(unittest.TestCase):
    """AdditionalEmailsReadableAttribute unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdditionalEmailsReadableAttribute(self):
        """Test AdditionalEmailsReadableAttribute"""
        # inst = AdditionalEmailsReadableAttribute()

if __name__ == '__main__':
    unittest.main()
