from pathlib import Path

class RequirementsConverter:
    def __init__(self, project_dir: str | Path, with_version: bool = True) -> None: ...
    @property
    def dependencies(self) -> list[str]: ...
    @property
    def requirements_txt_str(self) -> str: ...
    def save_as_requirements_txt(self) -> None: ...
