# -*- coding: utf-8 -*-

import enum


class TypeEnum(enum.Enum):
    annotation = "annotation"
    backgroundColor = "backgroundColor"
    blockCard = "blockCard"
    blockquote = "blockquote"
    border = "border"
    bulletList = "bulletList"
    code = "code"
    codeBlock = "codeBlock"
    date = "date"
    doc = "doc"
    em = "em"
    emoji = "emoji"
    expand = "expand"
    file = "file"
    hardBreak = "hardBreak"
    heading = "heading"
    inlineCard = "inlineCard"
    indentation = "indentation"
    link = "link"
    listItem = "listItem"
    media = "media"
    mediaGroup = "mediaGroup"
    mediaSingle = "mediaSingle"
    mention = "mention"
    nestedExpand = "nestedExpand"
    orderedList = "orderedList"
    panel = "panel"
    paragraph = "paragraph"
    rule = "rule"
    status = "status"
    strike = "strike"
    strong = "strong"
    sub = "sub"
    subsup = "subsup"
    table = "table"
    tableCell = "tableCell"
    tableHeader = "tableHeader"
    tableRow = "tableRow"
    taskItem = "taskItem"
    taskList = "taskList"
    text = "text"
    textColor = "textColor"
    underline = "underline"
