from _typeshed import Incomplete

MAX_INT16: Incomplete
MIN_INT16: Incomplete

def bytes2bin(bites: bytes, sz: int = 8) -> bytearray: ...
def bin2bytes(x: bytes) -> bytes: ...
def bin2dec(x: bytes) -> int: ...
def bytes2dec(bites: bytes, sz: int = 8) -> int: ...
def dec2bin(n: int, p: int = 1) -> bytearray: ...
def dec2bytes(n: int, p: int = 1) -> bytes: ...
def bin2synchsafe(x: bytes) -> bytearray: ...
def bytes2signedInt16(bites: bytes) -> int: ...
def signedInt162bytes(n: int) -> bytes: ...
