EARLIEST_LEDGER_SEQ = 87570565  # first Post Fiat ledger on XRPL mainnet

TOKEN = 'PFT'
TOKEN_ISSUER = 'rnQUEEg8yyjrwk9FhyXpKavHyCRJM9BDMW'

TASK_NODE_ADDRESS = 'r4yc85M1hwsegVGZ1pawpZPwj65SVs8PzD'
REMEMBRANCER_ADDRESS = 'rJ1mBMhEBKack5uTQvM8vWoAntbufyG9Yn'
