# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: foreverbull/service/instance.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'foreverbull/service/instance.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"foreverbull/service/instance.proto\x12\x13\x66oreverbull.service\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x03\n\x08Instance\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x12\n\x05Image\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04Host\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x11\n\x04Port\x18\x04 \x01(\x05H\x02\x88\x01\x01\x12\x36\n\x08statuses\x18\x05 \x03(\x0b\x32$.foreverbull.service.Instance.Status\x1a\xf0\x01\n\x06Status\x12;\n\x06status\x18\x01 \x01(\x0e\x32+.foreverbull.service.Instance.Status.Status\x12\x12\n\x05\x65rror\x18\x02 \x01(\tH\x00\x88\x01\x01\x12.\n\nOccurredAt\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"[\n\x06Status\x12\x0b\n\x07\x43REATED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\x0e\n\nCONFIGURED\x10\x02\x12\r\n\tEXECUTING\x10\x03\x12\r\n\tCOMPLETED\x10\x04\x12\t\n\x05\x45RROR\x10\x05\x42\x08\n\x06_errorB\x08\n\x06_ImageB\x07\n\x05_HostB\x07\n\x05_PortB2Z0github.com/lhjnilsson/foreverbull/pkg/pb/serviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'foreverbull.service.instance_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z0github.com/lhjnilsson/foreverbull/pkg/pb/service'
  _globals['_INSTANCE']._serialized_start=93
  _globals['_INSTANCE']._serialized_end=500
  _globals['_INSTANCE_STATUS']._serialized_start=232
  _globals['_INSTANCE_STATUS']._serialized_end=472
  _globals['_INSTANCE_STATUS_STATUS']._serialized_start=371
  _globals['_INSTANCE_STATUS_STATUS']._serialized_end=462
# @@protoc_insertion_point(module_scope)
