from _typeshed import Incomplete
from ycf.cli import settings as settings
from ycf.cli.sources.mapping import get_source as get_source
from ycf.cli.yc.client import YandexCloudClient as YandexCloudClient
from ycf.cli.yc.dto import YandexCloudFunctionRelease as YandexCloudFunctionRelease

class DeployManager:
    yc_client: Incomplete
    source: Incomplete
    def __init__(self) -> None: ...
    def auth(self) -> None: ...
    def build(self) -> None: ...
    def upload(self) -> None: ...
    def release(self) -> None: ...
    def clean(self) -> None: ...
