
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2025-03-05T04:59:50+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "135b5acb6f50ea9cca398f60a576cf46f46d60b1",
 "version": "0.11.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
